//! The checked-in TypeScript derived from the Rust wire DTOs.
//!
//! The frontend never hand-writes a wire type. This module renders exactly one artifact — the
//! declarations the React application imports — and a test asserts the checked-in copy still
//! matches, so a Rust field rename fails the build rather than reaching an operator as a blank
//! panel.

use std::{fs, io, path::Path};

use ts_rs::{Config, TS};

use crate::error::ApiErrorBody;
use crate::wire::{
    AddressView, AudioBandsView, AudioPanelView, AudioSettingsView, AudioView,
    AvailableMonitorView, CatalogFolderView, CatalogItemView, CatalogView, CreateText,
    CreateVisualizer, DeleteText, DeskIdentityView, DmxChannelGroupView, DmxChannelView,
    DmxIngressView, DmxMapView, DmxPersonalityView, DmxResolutionView, DmxValueSetView,
    EffectParameterView, EffectSlotView, FolderPresentationView, FolderPresentationsView, Health,
    ImportJobView, ImportsView, LayerView, LogRecordView, LogsView, MaskView, MasterView,
    NetworkAddressesView, NetworkView, OutputConfigurationValuesView, OutputConfigurationView,
    OutputView, PendingImportView, RemoveFolderPicture, RunningOutputView, RunningServerView,
    ServerLogLevelView, SourceStatusView, StartImport, TelemetryFrame, TextFormatView,
    TextSlotView, TextStyleView, TimeView, UpdateAudio, UpdateFolderPresentation, UpdateLayer,
    UpdateLibraryFolder, UpdateLibraryItem, UpdateMaster, UpdateNetwork, UpdateOutputConfiguration,
    UpdateServerLogLevel, UpdateText, UpdateTime, UpdateVisualizer, UploadAcceptedView,
    VisualizerParametersView, VisualizerView, WaveformView,
};

const TYPESCRIPT_PATH: &str = "apps/media/src/shared/api/generated/media-wire.ts";

/// One generated artifact, relative to the workspace root.
#[derive(Debug, Eq, PartialEq)]
pub struct GeneratedArtifact {
    pub path: String,
    pub contents: String,
}

/// Renders every checked-in artifact without touching the filesystem.
pub fn generated_artifacts() -> Vec<GeneratedArtifact> {
    vec![GeneratedArtifact {
        path: TYPESCRIPT_PATH.into(),
        contents: typescript_bindings(),
    }]
}

pub fn write_generated_artifacts(workspace_root: &Path) -> io::Result<()> {
    for artifact in generated_artifacts() {
        let destination = workspace_root.join(&artifact.path);
        if let Some(parent) = destination.parent() {
            fs::create_dir_all(parent)?;
        }
        fs::write(destination, artifact.contents)?;
    }
    Ok(())
}

fn typescript_bindings() -> String {
    let config = Config::default();
    let declarations = declarations(&config)
        .into_iter()
        .map(export_declaration)
        .collect::<Vec<_>>()
        .join("\n");
    format!(
        "// This file is generated by `cargo run -p media-http --example generate-contracts`.\n\
         // Do not edit it by hand.\n\n{declarations}\n"
    )
}

fn declarations(config: &Config) -> Vec<String> {
    vec![
        ApiErrorBody::decl(config),
        Health::decl(config),
        RunningOutputView::decl(config),
        RunningServerView::decl(config),
        AddressView::decl(config),
        SourceStatusView::decl(config),
        MaskView::decl(config),
        EffectParameterView::decl(config),
        EffectSlotView::decl(config),
        LayerView::decl(config),
        MasterView::decl(config),
        OutputView::decl(config),
        AvailableMonitorView::decl(config),
        OutputConfigurationValuesView::decl(config),
        OutputConfigurationView::decl(config),
        DmxMapView::decl(config),
        DmxIngressView::decl(config),
        DmxPersonalityView::decl(config),
        DmxChannelView::decl(config),
        DmxChannelGroupView::decl(config),
        DmxResolutionView::decl(config),
        DmxValueSetView::decl(config),
        CatalogItemView::decl(config),
        CatalogFolderView::decl(config),
        CatalogView::decl(config),
        FolderPresentationView::decl(config),
        FolderPresentationsView::decl(config),
        VisualizerParametersView::decl(config),
        VisualizerView::decl(config),
        NetworkAddressesView::decl(config),
        NetworkView::decl(config),
        TimeView::decl(config),
        TextStyleView::decl(config),
        TextFormatView::decl(config),
        TextSlotView::decl(config),
        AudioBandsView::decl(config),
        WaveformView::decl(config),
        AudioView::decl(config),
        AudioSettingsView::decl(config),
        AudioPanelView::decl(config),
        PendingImportView::decl(config),
        ImportJobView::decl(config),
        ImportsView::decl(config),
        DeskIdentityView::decl(config),
        TelemetryFrame::decl(config),
        LogRecordView::decl(config),
        LogsView::decl(config),
        ServerLogLevelView::decl(config),
        UpdateLayer::decl(config),
        UpdateMaster::decl(config),
        UpdateOutputConfiguration::decl(config),
        CreateVisualizer::decl(config),
        UpdateVisualizer::decl(config),
        UpdateNetwork::decl(config),
        UpdateTime::decl(config),
        CreateText::decl(config),
        UpdateText::decl(config),
        DeleteText::decl(config),
        UpdateAudio::decl(config),
        StartImport::decl(config),
        UpdateLibraryItem::decl(config),
        UpdateLibraryFolder::decl(config),
        UpdateFolderPresentation::decl(config),
        RemoveFolderPicture::decl(config),
        UpdateServerLogLevel::decl(config),
        UploadAcceptedView::decl(config),
    ]
}

fn export_declaration(declaration: String) -> String {
    let declaration = declaration
        .lines()
        .map(str::trim_end)
        .collect::<Vec<_>>()
        .join("\n");
    format!("export {declaration}")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_declaration_is_exported_and_named() {
        let bindings = typescript_bindings();
        assert!(bindings.contains("export type OutputView"));
        assert!(bindings.contains("export type UpdateLayer"));
        assert!(
            bindings.contains("Do not edit it by hand"),
            "a generated file must say so"
        );
    }
}
