import { fixtures } from "../data/mockData";
import { SourceValue } from "../components/shared/SourceValue";
import type { WindowProps } from "./windowTypes";
import { useServer } from "../api/ServerContext";
import { useApp } from "../state/AppContext";

export function FixtureSheetWindow({ compact }: WindowProps) {
  const server = useServer();
  const { dispatch } = useApp();
  const liveFixtures = server.patch?.fixtures.map((patched, index) => ({ ...fixtures[index % fixtures.length], id: index + 1, name: patched.definition.name ?? patched.definition.model, type: `${patched.definition.manufacturer} · ${patched.definition.mode} · U${patched.universe}.${patched.address}`, fixtureId: patched.fixture_id, limitingGroups: server.groups.filter((group) => group.body.playback_fader != null && (group.body.fixtures.includes(patched.fixture_id) || patched.logical_heads.some((head) => group.body.fixtures.includes(head.fixture_id))) && (group.body.master ?? 1) < 1) })) ?? [];
  const rows = server.bootstrap ? liveFixtures : fixtures.map((fixture) => ({ ...fixture, fixtureId: "", limitingGroups: [] }));
  const visible = compact ? rows.slice(0, 12) : rows;
  return <div className="fixture-window"><header className="window-toolbar"><h1>Fixture Sheet {!compact && <small>{server.selectedFixtures.length} selected</small>}</h1><span className="source-legend"><i className="source-programmer">● Programmer</i><i className="source-playback">● Playback</i><i className="source-default">● Default</i></span><span className="spacer"/>{!compact && <div className="button-group"><button onClick={() => dispatch({ type: "OPEN_BUILTIN", kind: "groups" })}>Groups</button><button className="active" disabled>Fixtures</button></div>}</header><div className="fixture-table"><div className="fixture-row fixture-head"><span>ID</span><span>Name / type</span><span>Dimmer</span><span>Color</span><span>Position</span><span>Beam</span><span>Focus</span></div>{visible.length === 0 && <div className="empty-window-message">No fixtures are patched in the active show.</div>}{visible.map((fixture) => <button onClick={() => fixture.fixtureId && void server.setSelection([fixture.fixtureId])} className={`fixture-row ${fixture.fixtureId && server.selectedFixtures.includes(fixture.fixtureId) ? "selected" : ""}`} key={fixture.fixtureId || fixture.id}><span>{fixture.id}</span><span className="fixture-name"><b>{fixture.name}</b><small>{fixture.type}</small>{fixture.limitingGroups.length > 0 && <em title={fixture.limitingGroups.map((group) => `${group.body.name}: ${Math.round((group.body.master ?? 1) * 100)}%`).join(", ")}>◒ Group master {Math.round(Math.max(...fixture.limitingGroups.map((group) => group.body.master ?? 1)) * 100)}%</em>}</span><SourceValue source={fixture.sources.dimmer}><i className="vertical-meter"><i style={{ height: `${fixture.dimmer}%` }}/></i>{fixture.dimmer}%</SourceValue><SourceValue source={fixture.sources.color}><i className="color-dot" style={{ background: fixture.color }}/>{fixture.colorLabel}</SourceValue><SourceValue source={fixture.sources.position}><i className="position-glyph"><i style={{ left: `${fixture.pan % 75}%`, top: `${fixture.tilt % 65}%` }}/></i>{fixture.positionLabel ?? `${fixture.pan}° / ${fixture.tilt}°`}</SourceValue><SourceValue source={fixture.sources.beam}>{fixture.beam}</SourceValue><SourceValue source={fixture.sources.focus}>{fixture.focus}</SourceValue></button>)}</div></div>;
}
