import { useEffect, useMemo, useRef, useState } from "react";
import type { WindowProps } from "./windowTypes";
import { useServer } from "../api/ServerContext";
import type { AttributeValue, VisualizationSnapshot } from "../api/types";
import { cueVisualization, migrateStagePosition, renderStageThumbnail } from "./stage3dScene";
import { Button, Input, Select } from "../components/common";

export function PlaybackWindow({ compact, playbackTab }: WindowProps) {
  const server = useServer();
  const [tab, setTab] = useState<"pool" | "cues">(playbackTab ?? "pool");
  const [selectedPlayback, setSelectedPlayback] = useState<number>(1);
  const [search, setSearch] = useState("");
  const [settingsOpen, setSettingsOpen] = useState(false);
  const [poolMessage, setPoolMessage] = useState("");
  const holdTimer = useRef<number | null>(null);
  const held = useRef(false);
  const selectedDefinition = server.playbacks?.pool.find((playback) => playback.number === selectedPlayback);
  const selectedCueListId = selectedDefinition?.target.type === "cue_list" ? selectedDefinition.target.cue_list_id : null;
  const sequence = selectedCueListId ? server.playbacks?.cue_lists.find((cue) => cue.id === selectedCueListId) : server.playbacks?.cue_lists[0];
  const active = sequence && server.playbacks?.active.find((item) => item.cue_list_id === sequence.id);
  const cues = sequence?.cues ?? [];
  const [selectedCue, setSelectedCue] = useState(0);
  const tauri = typeof window !== "undefined" && "__TAURI_INTERNALS__" in window;
  const [thumbnails, setThumbnails] = useState<Record<number, string>>({});
  const stageFixtures = useMemo(() => (server.patch?.fixtures ?? []).flatMap((fixture, fixtureIndex) => [{id:fixture.fixture_id,location:fixture.location,rotation:fixture.rotation}, ...(fixture.multipatch ?? [])].map((instance,instanceIndex) => { const index=fixtureIndex*16+instanceIndex; const located=instance.location&&(instance.location.x||instance.location.y||instance.location.z)?{x:instance.location.x/1000,y:instance.location.y/1000,z:instance.location.z/1000,rotationX:instance.rotation?.x??0,rotationY:instance.rotation?.y??0,rotationZ:instance.rotation?.z??0}:null; return {fixture,instanceId:instance.id,index,position:server.stageLayout?.body.positions3d?.[instance.id]??located??migrateStagePosition(instanceIndex?undefined:server.stageLayout?.body.positions[fixture.fixture_id],index)}; })), [server.patch, server.stageLayout]);
  useEffect(() => {
    if (!tauri || !cues.length || !stageFixtures.length) return;
    let cancelled = false;
    void server.readVisualization().then((live) => {
      if (cancelled) return;
      let state: VisualizationSnapshot = { ...live, values: [] };
      const next: Record<number, string> = {};
      for (let index = 0; index < cues.length; index++) {
        const changes = [...(cues[index].changes ?? [])] as Array<{ fixture_id: string; attribute: string; value: AttributeValue | null }>;
        for (const groupChange of cues[index].group_changes ?? []) {
          const group = server.groups.find((candidate) => candidate.id === groupChange.group_id);
          for (const fixture_id of group?.body.fixtures ?? []) changes.push({ fixture_id, attribute: groupChange.attribute, value: groupChange.value });
        }
        state = cueVisualization(state, changes);
        next[index] = renderStageThumbnail(stageFixtures, state);
      }
      if (!cancelled) setThumbnails(next);
    }).catch(() => undefined);
    return () => { cancelled = true; };
  }, [tauri, cues, stageFixtures, server.groups, server.readVisualization]);
  const settings = settingsOpen && selectedDefinition && <div className="modal-backdrop playback-settings-backdrop" onPointerDown={(event) => event.target === event.currentTarget && setSettingsOpen(false)}><section className="modal-card playback-settings-modal"><Button className="modal-close" onClick={() => setSettingsOpen(false)}>×</Button><h2>{selectedDefinition.number} · {selectedDefinition.name}</h2><label><Input type="checkbox" checked={selectedDefinition.go_activates} onChange={(event) => void server.savePlaybackDefinition({ ...selectedDefinition, go_activates: event.target.checked })}/> Go turns playback on</label><label><Input type="checkbox" checked={selectedDefinition.auto_off} onChange={(event) => void server.savePlaybackDefinition({ ...selectedDefinition, auto_off: event.target.checked })}/> Switch off when fully overwritten</label><label>X-fade milliseconds<Input type="number" min="0" max="60000" value={selectedDefinition.xfade_millis} onChange={(event) => void server.savePlaybackDefinition({ ...selectedDefinition, xfade_millis: Number(event.target.value) })}/></label><label>Fader<Select value={selectedDefinition.fader} onChange={(event) => void server.savePlaybackDefinition({ ...selectedDefinition, fader: event.target.value as typeof selectedDefinition.fader })}><option value="master">Master</option><option value="temp">Temp</option><option value="speed" disabled>Speed (future)</option></Select></label>{selectedDefinition.buttons.map((action, index) => <label key={index}>Button {index + 1}<Select value={action} onChange={(event) => { const buttons = [...selectedDefinition.buttons] as typeof selectedDefinition.buttons; buttons[index] = event.target.value as typeof action; void server.savePlaybackDefinition({ ...selectedDefinition, buttons }); }}>{["none","on","off","toggle","go","go_minus","flash"].map((value) => <option key={value} value={value}>{value.replace("_", " ")}</option>)}</Select></label>)}</section></div>;
  if (tab === "pool") return <div className="playback-window pool-window"><header className="window-toolbar"><h1>Playback Pool <small>{server.playbacks?.pool.length ?? 0} / 1000 assigned</small></h1><span className="spacer"/><label className="playback-search"><span>⌕ Search playbacks</span><Input aria-label="Search playbacks" placeholder="Number or name" value={search} onChange={(event) => setSearch(event.target.value)}/></label></header>{poolMessage && <div className="pool-message">{poolMessage}</div>}<div className="card-pool playback-pool-grid">{(server.playbacks?.pool ?? []).filter((playback) => !search || playback.name.toLowerCase().includes(search.toLowerCase()) || String(playback.number).includes(search)).map((playback) => { const runtime = server.playbacks?.active.find((item) => item.playback_number === playback.number); const usage = (server.playbacks?.pages ?? []).filter((page) => Object.values(page.slots).includes(playback.number)).map((page) => page.number); return <Button key={playback.number} className={`pool-cell playback-card ${runtime ? "running" : ""} ${selectedPlayback === playback.number ? "selected" : ""}`} onPointerDown={() => { held.current = false; holdTimer.current = window.setTimeout(() => { held.current = true; setSelectedPlayback(playback.number); setSettingsOpen(true); }, 650); }} onPointerUp={() => { if (holdTimer.current) window.clearTimeout(holdTimer.current); holdTimer.current = null; }} onPointerCancel={() => { if (holdTimer.current) window.clearTimeout(holdTimer.current); holdTimer.current = null; }} onContextMenu={(event) => event.preventDefault()} onClick={() => { if (held.current) { held.current = false; return; } setSelectedPlayback(playback.number); if (playback.target.type === "cue_list") { setPoolMessage(""); setTab("cues"); } else setPoolMessage(`${playback.number} · ${playback.name}: No cue list assigned`); }}><span className="number">{playback.number}</span><b>{playback.name}</b><small>{playback.target.type === "cue_list" ? "Cue list" : "Group"} · {runtime ? `${Math.round(runtime.master * 100)}%` : "Off"}</small><small>{usage.length ? `Pages ${usage.join(", ")}` : "Not on a page"}</small></Button>; })}</div>{settings}</div>;
  return <div className="playback-window"><header className="window-toolbar sequence-toolbar"><h1>Sequence · {sequence?.name ?? "No sequence"} <small>{active ? "Running" : "Ready"} · revision {server.patch?.revision ?? 0}</small></h1><span className="spacer"/>{sequence && <span>{sequence.mode} · priority {sequence.priority}</span>}<Button className="back-to-playback-pool" onClick={() => setTab("pool")}>← Back to Playback Pool</Button></header><div className="sequence-layout"><div className="cue-editor"><div className="cue-table-wrap">{cues.length === 0 ? <div className="empty-window-message">No cue list is available in the active show.</div> : <table className="cue-table"><thead><tr><th>Preview</th><th>No.</th><th>Name</th><th>Trigger</th><th>Fade</th><th>Status</th></tr></thead><tbody>{cues.map((cue,index)=><tr tabIndex={0} onClick={()=>setSelectedCue(index)} onKeyDown={(event)=>{if(event.key==="Enter"||event.key===" "){event.preventDefault();setSelectedCue(index);}}} key={cue.number} className={`${active?.cue_index===index?"current":active?.cue_index===index-1?"next":""} ${selectedCue===index?"selected":""}`}><td>{thumbnails[index]&&<img src={thumbnails[index]} alt=""/>}</td><td><b>{cue.number}</b></td><td>{cue.name||`Cue ${cue.number}`}</td><td>{cue.trigger.type}</td><td>{(cue.fade_millis/1000).toFixed(1)} s</td><td>{index===active?.cue_index?"Active":"Tracked"}</td></tr>)}</tbody></table>}</div></div>{!compact && <aside className="sequence-actions"><Button className="go" disabled={!selectedDefinition} onClick={() => selectedDefinition && void server.poolPlaybackAction(selectedDefinition.number, "go")}>GO<br/><small>{sequence ? `Next · ${cues[(active?.cue_index ?? -1) + 1]?.name ?? "End"}` : "No sequence"}</small></Button><Button disabled={!selectedDefinition} onClick={() => selectedDefinition && void server.poolPlaybackAction(selectedDefinition.number, "go-minus")}>GO −</Button><Button disabled={!selectedDefinition} onClick={() => selectedDefinition && void server.poolPlaybackAction(selectedDefinition.number, "toggle")}>TOGGLE</Button><Button disabled={!selectedDefinition} onClick={() => selectedDefinition && void server.poolPlaybackAction(selectedDefinition.number, "off")}>OFF</Button>{sequence && cues[selectedCue] && <section>{thumbnails[selectedCue] && <img className="cue-selected-thumbnail" src={thumbnails[selectedCue]} alt={`3D preview for cue ${cues[selectedCue].number}`}/>}<b>Selected cue · {cues[selectedCue].number}</b><p>{cues[selectedCue].name || "Unnamed cue"}</p><small>Fade {(cues[selectedCue].fade_millis / 1000).toFixed(1)} s · Delay {(cues[selectedCue].delay_millis / 1000).toFixed(1)} s</small></section>}</aside>}</div></div>;
}
