// What the desk is doing to this server.
//
// This page answers one question an operator asks at a patch bay: is anything actually arriving,
// and is it landing where I think it is. It reports; it does not control.

import { WindowFrame } from "@tosklight/ui/window-kit";
import { useEffect, useState } from "react";
import { ResourceState } from "../../app/ResourceState";
import { addressLabel } from "../../entities/catalog";
import { percent, sourceBadge } from "../../entities/output";
import { ApiFailure, api } from "../../shared/api/client";
import type {
	DmxChannelView,
	DmxIngressView,
	DmxMapView,
	OutputView,
} from "../../shared/api/generated/media-wire";
import { useNetwork, useOutputs } from "../../shared/api/queries";
import { useTelemetry } from "../../shared/api/telemetry";

export function DmxPage() {
	const outputs = useOutputs();
	const telemetry = useTelemetry();
	const [connectOpen, setConnectOpen] = useState(false);

	return (
		<WindowFrame
			title="Diagnostics"
			className="media-dmx-window"
			info={{ primary: "DMX", secondary: "Input and channel diagnostics" }}
			groups={[
				{
					id: "dmx-diagnostics-actions",
					actions: [
						{
							id: "connect-console",
							label: "Connect to Console",
							variant: "primary",
							active: connectOpen,
							className: "media-connect-console",
							onPress: () => setConnectOpen((open) => !open),
						},
						{
							id: "configure-dmx-input",
							label: "Configure DMX input",
							onPress: () => {
								window.history.pushState(null, "", "/settings?section=dmx");
								window.dispatchEvent(new PopStateEvent("popstate"));
							},
						},
					],
				},
			]}
		>
			<section className="media-page media-dmx-content">
				{connectOpen && <ConsoleConnection outputs={outputs.data ?? []} />}
				<ResourceState
					resource={outputs}
					subject="outputs"
					isEmpty={(data) => data.length === 0}
					empty="This server has no enabled outputs, so nothing is listening for a desk."
				>
					{(data) =>
						data.map((output) => (
							<OutputDmx
								key={output.id}
								output={output}
								ingress={telemetry.frame?.dmx.find(
									(sample) => sample.outputId === output.id,
								)}
							/>
						))
					}
				</ResourceState>
			</section>
		</WindowFrame>
	);
}

function ConsoleConnection({ outputs }: { outputs: OutputView[] }) {
	const [consoleName, setConsoleName] = useState("MagicQ");
	const [fixtures, setFixtures] = useState<string[]>();
	const [failure, setFailure] = useState<string>();
	const network = useNetwork();
	useEffect(() => {
		let current = true;
		void api
			.fixtures()
			.then((names) => {
				if (current) setFixtures(names);
			})
			.catch((error: unknown) => {
				if (current) setFailure(String(error));
			});
		return () => {
			current = false;
		};
	}, []);
	const extension =
		consoleName === "MagicQ"
			? ".hed"
			: consoleName === "grandMA2"
				? ".xml"
				: ".gdtf";
	const files = fixtures?.filter((name) => name.endsWith(extension));
	return (
		<section className="media-settings-section" aria-label="Connect to Console">
			<h2>Connect to Console</h2>
			<label>
				Console{" "}
				<select
					value={consoleName}
					onChange={(event) => setConsoleName(event.target.value)}
				>
					{["MagicQ", "grandMA2", "grandMA3", "GDTF"].map((name) => (
						<option key={name}>{name}</option>
					))}
				</select>
			</label>
			<h3>{consoleName} personalities</h3>
			<p>
				These downloads are generated by this running Pixel server from its
				canonical DMX definition. Patch eight separate ToskLight Pixel Layer
				fixtures and one ToskLight Pixel Master fixture.
			</p>
			{!fixtures && !failure && (
				<p role="status">Loading generated personalities…</p>
			)}
			{failure && (
				<p role="alert">
					Could not load personalities: {failure}. Close and reopen Connect to
					Console to retry.
				</p>
			)}
			{files?.length === 0 && (
				<p role="alert">
					No generated personalities are available for this console.
				</p>
			)}
			<div className="media-settings-actions">
				{files?.map((name) => (
					<a
						className="ui-button ui-secondary ui-default"
						href={api.fixtureUrl(name)}
						download
						key={name}
					>
						Download {name}
					</a>
				))}
			</div>
			<h3>Configured footprint and patch addresses</h3>
			<p>
				Choose eight layers and Effect banks and full master controls in
				Settings → DMX. Apply pending changes by restarting Pixel before
				downloading and patching. Earlier channel layouts require migration to
				the full master layout for these generated personalities.
			</p>
			{outputs.length === 0 && (
				<p>No enabled outputs. Configure an output in Settings first.</p>
			)}
			{outputs.map((output) => (
				<ConsolePatch key={output.id} output={output} />
			))}
			<ConsoleTutorial consoleName={consoleName} />
			<ResourceState resource={network} subject="network settings">
				{(value) => (
					<>
						<h3>Active network listeners</h3>
						<dl className="media-facts">
							<dt>sACN (UDP)</dt>
							<dd>{value.resolved.sacnListen}</dd>
							<dt>Art-Net (UDP)</dt>
							<dd>{value.resolved.artNetListen}</dd>
							<dt>CITP/MSEX (TCP)</dt>
							<dd>
								{value.resolved.citpListen}; advertised port{" "}
								{value.citpAdvertisedPort}
							</dd>
							<dt>Pixel interface (HTTP)</dt>
							<dd>{value.resolved.httpListen}</dd>
						</dl>
						{value.pendingRestart && (
							<p role="alert">
								Network changes are pending. Restart Pixel before connecting.
							</p>
						)}
					</>
				)}
			</ResourceState>
		</section>
	);
}

function ConsoleTutorial({ consoleName }: { consoleName: string }) {
	return (
		<>
			<h3>{consoleName} connection tutorial</h3>
			<ol>
				<li>
					{consoleName === "MagicQ"
						? "Save the two native .hed downloads in MagicQ’s show/heads folder. In a new empty show, open PATCH, choose the ToskLight manufacturer and Pixel Layer, and patch eight heads. Choose Pixel Master and patch one head separately. If the heads are missing, rescan/restart MagicQ after copying the files."
						: consoleName === "grandMA2"
							? "Copy both XML downloads to gma2/library on the selected drive. In Setup → Patch & Fixture Schedule, import the Layer and Master fixture types; add eight Layer fixtures and one Master fixture."
							: consoleName === "grandMA3"
								? "In Patch, import both GDTF downloads as fixture types. Add eight Pixel Layer fixtures and one Pixel Master fixture."
								: "Use your console’s GDTF fixture-type import to load both downloads, then add eight Layer fixtures and one Master fixture. Import menu names depend on the console."}
				</li>
				<li>
					Use the universe and start address in the patch table for each head.
					Each layer has its own block; the Master begins immediately after the
					final layer. Do not patch the Master at the first layer address.
				</li>
				<li>
					{consoleName === "MagicQ"
						? "In SETUP → View DMX I/O, enable sACN output for the patched universe and send it to Pixel’s network address. Match Pixel’s protocol and universe in Settings → DMX. "
						: "Enable sACN output for the patched universe and send it to Pixel’s network address. Match Pixel’s protocol and universe in Settings → DMX. "}
					For Art-Net, select Art-Net at both ends and check the console’s
					zero-based wire-universe convention. sACN universe numbers start at 1.
				</li>
				<li>
					{consoleName === "MagicQ"
						? "Open SETUP → View System → Media. Choose CITP MSEX, set Pixel’s address and advertised CITP port, set first layer head to 1 and Layers to 8 (use consecutive Layer head numbers 1–8; Master is head 9). Set Thumbs to Enabled and Live prev to Yes, then GET THUMBS. "
						: "Where your console supports CITP/MSEX, add Pixel as a media server using its address and advertised CITP port, associate the Layer fixtures in order, and request the media library and previews. "}
					GDTF and DMX import alone do not enable CITP; console support and
					media-server setup are required.
				</li>
				<li>
					Same computer:{" "}
					{consoleName === "MagicQ" &&
						"in MagicQ SETUP → View Settings, set Net host options to Normal + Loopback IP (called Send to applications on this PC in older versions). "}
					Enable Pixel’s Same computer network preset, restart it, and use
					127.0.0.1 for the console destination and CITP endpoint. Prefer
					explicit unicast sACN. If the console cannot send over loopback,
					disable the preset and use this computer’s reachable LAN address at
					both ends. Select the matching console network interface. A listener
					bind error must be resolved before testing. For same-computer Art-Net,
					keep Pixel’s Art-Net listener on 127.0.0.1 so it can share UDP 6454
					with the console; use sACN for the LAN-address fallback.
				</li>
				<li>
					Different computers: disable Same computer, bind Pixel to the
					lighting-network interface or 0.0.0.0, restart, and set the console
					destination to Pixel’s actual LAN IP (never 127.0.0.1 or 0.0.0.0).
					Select the same reachable lighting network at the console.{" "}
					{consoleName === "MagicQ" &&
						"For a LAN-address connection (including both programs on one computer using its LAN IP), set MagicQ’s IP address to the active LAN interface and Net host options to Normal, without Loopback IP. "}
					For automatic discovery both computers must receive multicast on that
					interface; otherwise enter Pixel’s IP and port manually.
				</li>
				<li>
					Allow sACN UDP 5568 or Art-Net UDP 6454 to Pixel. Allow CITP discovery
					and live previews on UDP 4809 (multicast 224.0.0.180) on both peers,
					and the advertised CITP TCP port below. Allow Pixel’s configured HTTP
					port when opening its interface from another computer. Use the actual
					configured ports if changed; check macOS Local Network permissions and
					firewall rules on both computers.
				</li>
				<li>
					Release Pixel’s web playback takeover. Raise Master Dimmer and one
					Layer Dimmer, set Play Mode, and select a known Media Folder/File on
					the console. Pixel’s DMX page must show the expected sender, protocol,
					changing raw values; its output must visibly show the selected media.
				</li>
				<li>
					{consoleName === "MagicQ"
						? "In MagicQ’s Media window, select Layers 1–8 in turn. Verify the same encoder pages on every layer, with unused wheels blank. Folder/File and Mask Folder/File must advance one index at a time (0–255). "
						: "Select each layer and check individual folder/file steps. "}
					{consoleName === "MagicQ" &&
						"The normal preview shows master/program output. Hold SHIFT and press VIEW SERVERS (the soft button becomes PREVIEW LAYER) to switch to the selected layer’s live preview. Select Layers 1–8 in turn and confirm moving content in that preview belongs to each selected layer; switch back to check master/program output. The top layer strip shows static thumbnail indicators, not eight live preview streams. "}
					Confirm actual identifiable thumbnail images, a visibly updating
					master/program preview, and eight distinct layer previews that match
					their layers. A connection message or “Finished retrieving thumbnails”
					is not visual proof. Select the Master head and confirm its dimmer and
					Layer Opacity Cycle affect the shared output.
				</li>
				<li>
					If DMX is absent, check output enablement, transport, universe,
					destination/interface and receive-port conflicts. If DMX arrives but
					the picture is wrong, check patch offsets, layer/master dimmers, Play
					Mode and takeover. For blank thumbnails or previews, check the CITP
					endpoint, server/head association and media addresses.{" "}
					{consoleName === "MagicQ"
						? "After changing media, press RELOAD THUMBS in MagicQ; it does not refresh automatically after Pixel’s library-change notification. "
						: "Reload the console’s media library after changes. "}
					Verify actual images again. Repeat using Pixel’s LAN address from
					another computer to validate network reachability.
				</li>
			</ol>
		</>
	);
}

function ConsolePatch({ output }: { output: OutputView }) {
	const map = useDmxMap(output.id);
	const blocks = new Map<string, number[]>();
	for (const channel of map.data?.channels ?? []) {
		const label =
			channel.group.kind === "layer"
				? `Layer ${channel.group.number}`
				: "Master";
		const addresses = blocks.get(label) ?? [];
		addresses.push(channel.absoluteChannel);
		blocks.set(label, addresses);
	}
	return (
		<section aria-label={`${output.name} console patch`}>
			<h4>{output.name}</h4>
			{map.failure && <p role="alert">{map.failure.message}</p>}
			{!map.data && !map.failure && (
				<p role="status">Loading patch addresses…</p>
			)}
			{map.data && (
				<>
					<p>
						Universe {map.data.universe}; {map.data.layerCount} layers;{" "}
						{map.data.channels.length} DMX slots. Addresses come from this
						running output’s decoder.
					</p>
					{map.data.layerCount !== 8 && (
						<p role="alert">
							This output is not configured for eight layers. Change Settings →
							DMX and restart before the eight-layer patch.
						</p>
					)}
					<table className="media-table">
						<caption>Suggested {output.name} patch</caption>
						<thead>
							<tr>
								<th>Head</th>
								<th>Universe</th>
								<th>Start address</th>
								<th>Last address</th>
								<th>Footprint</th>
							</tr>
						</thead>
						<tbody>
							{[...blocks].map(([label, addresses]) => (
								<tr key={label}>
									<td>{label}</td>
									<td>{map.data?.universe}</td>
									<td>{Math.min(...addresses)}</td>
									<td>{Math.max(...addresses)}</td>
									<td>{Math.max(...addresses) - Math.min(...addresses) + 1}</td>
								</tr>
							))}
						</tbody>
					</table>
				</>
			)}
		</section>
	);
}

function OutputDmx({
	output,
	ingress,
}: {
	output: OutputView;
	ingress?: DmxIngressView;
}) {
	const map = useDmxMap(output.id);
	const active = ingress?.active ?? output.dmxActive;
	return (
		<section className="media-output" aria-label={`${output.name} DMX`}>
			<h2>{output.name}</h2>
			<p className={`media-badge is-${active ? "good" : "neutral"}`}>
				{active
					? "A desk is sending to this output"
					: "No desk has sent to this output recently"}
			</p>
			{ingress && <IngressFacts ingress={ingress} />}

			<table className="media-table">
				<caption className="media-visually-hidden">
					Layer snapshot when this page opened on {output.name}
				</caption>
				<thead>
					<tr>
						<th scope="col">Layer</th>
						<th scope="col">Address</th>
						<th scope="col">Play mode</th>
						<th scope="col">Dimmer</th>
						<th scope="col">Source</th>
					</tr>
				</thead>
				<tbody>
					{output.layers.map((layer) => {
						const badge = sourceBadge(layer.sourceStatus);
						return (
							<tr key={layer.index}>
								<td>{layer.index + 1}</td>
								<td>
									{addressLabel(layer.address.folder, layer.address.file)}
								</td>
								<td>{layer.playMode}</td>
								<td>{percent(layer.dimmer)}</td>
								<td>{badge.label}</td>
							</tr>
						);
					})}
				</tbody>
			</table>

			<p>
				Decoded layer and master values are a snapshot from opening this page.
				Live received bytes appear in the channel map below.
			</p>
			<dl className="media-facts">
				<dt>Master dimmer</dt>
				<dd>{percent(output.master.dimmer)}</dd>
				<dt>Master volume</dt>
				<dd>{percent(output.master.volume)}</dd>
				<dt>Master tint</dt>
				<dd>
					R {percent(output.master.tintRed)} · G{" "}
					{percent(output.master.tintGreen)} · B{" "}
					{percent(output.master.tintBlue)}
				</dd>
				<dt>Flip and mirror</dt>
				<dd>{output.master.flipMirror}</dd>
				<dt>Master mask</dt>
				<dd>
					{output.master.mask.class === "blank"
						? "none"
						: addressLabel(output.master.mask.folder, output.master.mask.file)}
				</dd>
			</dl>

			{map.failure && (
				<p className="media-state is-error">{map.failure.message}</p>
			)}
			{map.data && <ChannelMap map={map.data} ingress={ingress} />}
		</section>
	);
}

function useDmxMap(output: string): {
	data?: DmxMapView;
	failure?: ApiFailure;
} {
	const [data, setData] = useState<DmxMapView>();
	const [failure, setFailure] = useState<ApiFailure>();
	useEffect(() => {
		let current = true;
		void api
			.dmxMap(output)
			.then((next) => current && setData(next))
			.catch((error: unknown) => {
				if (current)
					setFailure(
						error instanceof ApiFailure
							? error
							: new ApiFailure("unexpected-error", String(error), 0),
					);
			});
		return () => {
			current = false;
		};
	}, [output]);
	return { data, failure };
}

function IngressFacts({ ingress }: { ingress: DmxIngressView }) {
	return (
		<dl className="media-facts">
			<dt>Protocol</dt>
			<dd>{ingress.protocol === "art-net" ? "Art-Net" : "sACN"}</dd>
			<dt>Universe and start</dt>
			<dd>
				{ingress.universe}, address {ingress.startAddress}
			</dd>
			<dt>Winning source</dt>
			<dd>{ingress.source}</dd>
			<dt>Receive rate</dt>
			<dd>{ingress.framesPerSecond.toFixed(1)} fps</dd>
			<dt>Last received</dt>
			<dd>
				{ingress.ageMillis} ms ago{ingress.active ? "" : " — stale"}
			</dd>
		</dl>
	);
}

function ChannelMap({
	map,
	ingress,
}: {
	map: DmxMapView;
	ingress?: DmxIngressView;
}) {
	return (
		<table className="media-table">
			<caption>
				DMX channel map and latest raw values for {map.outputName}
			</caption>
			<thead>
				<tr>
					<th scope="col">Group</th>
					<th scope="col">Channel</th>
					<th scope="col">Name</th>
					<th scope="col">Raw</th>
					<th scope="col">Decoded</th>
				</tr>
			</thead>
			<tbody>
				{map.channels.map((channel) => {
					const value = rawValueOf(channel, map, ingress);
					return (
						<tr key={channel.absoluteChannel}>
							<td>
								{channel.group.kind === "layer"
									? `Layer ${channel.group.number}`
									: "Master"}
							</td>
							<td>{channel.absoluteChannel}</td>
							<td>{channel.name}</td>
							<td className="media-dmx-raw">{value ?? "—"}</td>
							<td>{describeValue(channel, value)}</td>
						</tr>
					);
				})}
			</tbody>
		</table>
	);
}

function rawValueOf(
	channel: DmxChannelView,
	map: DmxMapView,
	ingress?: DmxIngressView,
): number | undefined {
	if (!ingress) return undefined;
	const at = channel.absoluteChannel - map.startAddress;
	const coarse = ingress.slots[at];
	if (coarse === undefined) return undefined;
	if (channel.resolution === "coarse")
		return coarse * 256 + (ingress.slots[at + 1] ?? 0);
	return coarse;
}

function describeValue(channel: DmxChannelView, value?: number): string {
	if (!channel.implemented)
		return channel.implementationNote ?? "Not implemented";
	if (value === undefined) return "No frame received";
	const set = channel.valueSets.find(
		(candidate) =>
			value >= candidate.from &&
			value <= candidate.to &&
			(value - candidate.from) % candidate.step === 0,
	);
	return set?.name ?? String(value);
}
