//! Deterministic checked-in artifacts derived from the Rust wire DTOs.

use std::{fs, io, path::Path};

use schemars::{JsonSchema, generate::SchemaSettings};
use ts_rs::{Config, TS};

use crate::v2::command_line::{
    CommandAcceptedAction, CommandChoiceOption, CommandChoiceOptionId, CommandErrorResponse,
    CommandHttpSource, CommandKey, CommandKeyPhase, CommandKeyRequest, CommandLineChangedEvent,
    CommandLineResponse, CommandOperationOutcome, CommandOperationResponse, CommandTarget,
    CueMoveCopyChoice, CueMoveCopyChoiceType, CueTransferOperation, ExecuteCommandLineRequest,
    ReplaceCommandLineRequest,
};

const TYPESCRIPT_PATH: &str = "apps/control-ui/src/api/generated/light-wire.ts";
const SCHEMA_DIRECTORY: &str = "crates/wire/schemas/v2-command-line";

/// One generated artifact relative to the workspace root.
#[derive(Debug, Eq, PartialEq)]
pub struct GeneratedArtifact {
    pub path: String,
    pub contents: String,
}

/// Render every checked-in artifact without touching the filesystem.
pub fn generated_artifacts() -> Vec<GeneratedArtifact> {
    vec![
        GeneratedArtifact {
            path: TYPESCRIPT_PATH.into(),
            contents: typescript_bindings(),
        },
        request_schema_artifact::<ReplaceCommandLineRequest>("replace-command-line-request"),
        request_schema_artifact::<CommandKeyRequest>("command-key-request"),
        request_schema_artifact::<ExecuteCommandLineRequest>("execute-command-line-request"),
        response_schema_artifact::<CommandLineResponse>("command-line-response"),
        response_schema_artifact::<CommandOperationResponse>("command-operation-response"),
        response_schema_artifact::<CommandErrorResponse>("command-error-response"),
        response_schema_artifact::<CommandLineChangedEvent>("command-line-changed-event"),
    ]
}

/// Rewrite all generated artifacts below `workspace_root`.
pub fn write_generated_artifacts(workspace_root: &Path) -> io::Result<()> {
    for artifact in generated_artifacts() {
        let destination = workspace_root.join(&artifact.path);
        if let Some(parent) = destination.parent() {
            fs::create_dir_all(parent)?;
        }
        fs::write(destination, artifact.contents)?;
    }
    Ok(())
}

fn request_schema_artifact<T: JsonSchema>(name: &str) -> GeneratedArtifact {
    schema_artifact::<T>(name, SchemaSettings::draft2020_12().for_deserialize())
}

fn response_schema_artifact<T: JsonSchema>(name: &str) -> GeneratedArtifact {
    schema_artifact::<T>(name, SchemaSettings::draft2020_12().for_serialize())
}

fn schema_artifact<T: JsonSchema>(name: &str, settings: SchemaSettings) -> GeneratedArtifact {
    let schema = settings.into_generator().into_root_schema_for::<T>();
    let mut contents =
        serde_json::to_string_pretty(&schema).expect("JSON Schema always serializes as JSON");
    contents.push('\n');
    GeneratedArtifact {
        path: format!("{SCHEMA_DIRECTORY}/{name}.schema.json"),
        contents,
    }
}

fn typescript_bindings() -> String {
    let config = Config::default();
    let declarations = [
        CommandTarget::decl(&config),
        CommandKey::decl(&config),
        CommandKeyPhase::decl(&config),
        CommandAcceptedAction::decl(&config),
        CommandChoiceOptionId::decl(&config),
        CueTransferOperation::decl(&config),
        CueMoveCopyChoiceType::decl(&config),
        CommandHttpSource::decl(&config),
        CommandChoiceOption::decl(&config),
        CueMoveCopyChoice::decl(&config),
        ReplaceCommandLineRequest::decl(&config),
        CommandKeyRequest::decl(&config),
        ExecuteCommandLineRequest::decl(&config),
        CommandLineResponse::decl(&config),
        CommandOperationOutcome::decl(&config),
        CommandOperationResponse::decl(&config),
        CommandErrorResponse::decl(&config),
        CommandLineChangedEvent::decl(&config),
    ];
    let declarations = declarations
        .into_iter()
        .map(|declaration| format!("export {declaration}"))
        .collect::<Vec<_>>()
        .join("\n\n");
    format!(
        "// This file is generated by `cargo run -p light-wire --example generate-contracts`.\n\
         // Do not edit it by hand.\n\n{declarations}\n"
    )
}
