import { defineConfig } from "vitest/config";

export default defineConfig({
	test: {
		environment: "node",
		include: [
			"e2e/bench/clockScenario.test.ts",
			"e2e/bench/commandScenario.test.ts",
			"e2e/bench/discreteEncoderScenario.test.ts",
			"e2e/bench/cueDeletion.test.ts",
			"e2e/bench/dmxScenario.test.ts",
			"e2e/bench/fixtureDmx.test.ts",
			"e2e/bench/hardwareScenario.test.ts",
			"e2e/bench/encoderCatalog.test.ts",
			"e2e/bench/encoderScenario.test.ts",
			"e2e/bench/highlightScenario.test.ts",
			"e2e/bench/mapExistingPlaybackToSlot.test.ts",
			"e2e/bench/outputRuntime.test.ts",
			"e2e/bench/outputPacketScenario.test.ts",
			"e2e/bench/playbackRuntimeAction.test.ts",
			"e2e/bench/protocols.test.ts",
			"e2e/bench/programmerPreloadLifecycle.test.ts",
			"e2e/bench/programmerFadeScenario.test.ts",
			"e2e/bench/programmerPriority.test.ts",
			"e2e/bench/programmingSelection.test.ts",
			"e2e/bench/programmerValues.test.ts",
			"e2e/bench/presetRecall.test.ts",
			"e2e/bench/selectionScenario.test.ts",
			"e2e/bench/selectionRouteChoice.test.ts",
			"e2e/bench/selectionTransportScenario.test.ts",
			"e2e/bench/selectionVisibleScenario.test.ts",
			"e2e/bench/speedGroupRuntime.test.ts",
		],
	},
});
