import { defineConfig } from "vitest/config";

export default defineConfig({
	test: {
		environment: "node",
		include: [
			"e2e/bench/core/clockScenario.test.ts",
			"e2e/bench/command-selection/commandScenario.test.ts",
			"e2e/bench/encoders/discreteEncoderScenario.test.ts",
			"e2e/bench/playbacks/cueDeletion.test.ts",
			"e2e/bench/output/dmxScenario.test.ts",
			"e2e/bench/output/fixtureDmx.test.ts",
			"e2e/bench/hardware/hardwareScenario.test.ts",
			"e2e/bench/encoders/encoderCatalog.test.ts",
			"e2e/bench/encoders/encoderScenario.test.ts",
			"e2e/bench/programmer/highlightScenario.test.ts",
			"e2e/bench/playbacks/mapExistingPlaybackToSlot.test.ts",
			"e2e/bench/output/outputRuntime.test.ts",
			"e2e/bench/output/outputPacketScenario.test.ts",
			"e2e/bench/playbacks/playbackRuntimeAction.test.ts",
			"e2e/bench/core/protocols.test.ts",
			"e2e/bench/programmer/programmerPreloadLifecycle.test.ts",
			"e2e/bench/programmer/programmerFadeScenario.test.ts",
			"e2e/bench/programmer/programmerPriority.test.ts",
			"e2e/bench/command-selection/programmingSelection.test.ts",
			"e2e/bench/programmer/programmerValues.test.ts",
			"e2e/bench/groups-presets/presetRecall.test.ts",
			"e2e/bench/command-selection/selectionScenario.test.ts",
			"e2e/bench/command-selection/selectionRouteChoice.test.ts",
			"e2e/bench/command-selection/selectionTransportScenario.test.ts",
			"e2e/bench/command-selection/selectionVisibleScenario.test.ts",
			"e2e/bench/playbacks/speedGroupRuntime.test.ts",
		],
	},
});
