import type { VisualizerView } from "../../shared/api/generated/media-wire";

// Generated by media-render's visualizer_contact_sheet example. These are real off-screen frames
// from the same VisualizerRenderer and shaders used by program output, not browser approximations.
const previewModules = import.meta.glob<string>("./previews/*.png", {
	eager: true,
	query: "?url",
	import: "default",
});

const previewsByTypeId = new Map<number, string>();
for (const [path, url] of Object.entries(previewModules)) {
	const match = /\/(\d{3})-[^/]+\.png$/u.exec(path);
	if (match) previewsByTypeId.set(Number(match[1]), url);
}

/** Stable type IDs from media-domain, in the same family order as the shipped catalogue. */
export const BUILTIN_VISUALIZER_KINDS = [
	{ typeId: 0, label: "Equalizer Bars" },
	{ typeId: 1, label: "Waveform Oscilloscope" },
	{ typeId: 2, label: "Circular Spectrum" },
	{ typeId: 3, label: "Wave Terrain" },
	{ typeId: 10, label: "Pulsing Circles" },
	{ typeId: 11, label: "Morphing Polygon" },
	{ typeId: 12, label: "Minimalist Shapes" },
	{ typeId: 13, label: "Kaleidoscope" },
	{ typeId: 20, label: "Beat Explosions" },
	{ typeId: 21, label: "Dancing Swarm" },
	{ typeId: 22, label: "Starfield" },
	{ typeId: 23, label: "Lightning Tendrils" },
	{ typeId: 30, label: "Radiating Rays" },
	{ typeId: 31, label: "Strobe Flash" },
	{ typeId: 32, label: "Color Cycling" },
	{ typeId: 33, label: "Crossing Lines" },
	{ typeId: 40, label: "Digital Glitch" },
	{ typeId: 41, label: "CRT Scanline" },
	{ typeId: 42, label: "Matrix Digital Rain" },
	{ typeId: 50, label: "Rotating 3D Shape" },
	{ typeId: 51, label: "Fractal Morph" },
	{ typeId: 52, label: "City Tunnel" },
	{ typeId: 53, label: "Grid Landscape" },
] as const;

/** A representative frame rendered by the actual built-in visualizer implementation. */
export function visualizerPreviewUrl(
	visualizer: Pick<VisualizerView, "typeId">,
): string {
	return previewsByTypeId.get(visualizer.typeId) ?? "";
}

export function hasRenderedVisualizerPreview(typeId: number): boolean {
	return previewsByTypeId.has(typeId);
}
