[package]
name = "viz-render"
version.workspace = true
edition.workspace = true
license-file.workspace = true

[dependencies]
bytemuck.workspace = true
glam.workspace = true
pollster.workspace = true
viz-scene.workspace = true
wgpu.workspace = true

[dev-dependencies]
light-fixture = { path = "../../shared/fixture" }
naga = { version = "30", features = ["wgsl-in"] }
uuid.workspace = true
viz-project = { path = "../project" }

[lints]
workspace = true
