use super::super::*;

pub(super) fn recommended_builtin_placements() -> Vec<AttributePlacement> {
    use EncoderGroup::{Beam, Color, Control, Focus, Intensity, Media, Position, Shapers};

    [
        ("intensity", Intensity, 1, 1),
        ("shutter", Intensity, 1, 2),
        ("strobe", Intensity, 1, 3),
        ("volume", Intensity, 1, 4),
        ("color.red", Color, 1, 1),
        ("color.green", Color, 1, 2),
        ("color.blue", Color, 1, 3),
        ("color.white", Color, 1, 4),
        ("color.amber", Color, 1, 5),
        ("color.uv", Color, 1, 6),
        ("color.lime", Color, 2, 1),
        ("color.indigo", Color, 2, 2),
        ("color.mint", Color, 2, 3),
        ("color.temperature", Color, 2, 4),
        ("color.wheel.1", Color, 2, 5),
        ("color.wheel.2", Color, 2, 6),
        ("color.wheel.1.rotation", Color, 3, 1),
        ("color.wheel.2.rotation", Color, 3, 2),
        ("pan", Position, 1, 1),
        ("tilt", Position, 1, 2),
        ("pan.time", Position, 1, 5),
        ("tilt.time", Position, 1, 6),
        ("position.movement", Position, 1, 3),
        ("position.rotation", Position, 1, 4),
        ("camera.position.x", Position, 2, 1),
        ("camera.position.y", Position, 2, 2),
        ("camera.position.z", Position, 2, 3),
        ("camera.yaw", Position, 2, 4),
        ("camera.pitch", Position, 2, 5),
        ("camera.roll", Position, 2, 6),
        ("gobo.1", Beam, 1, 1),
        ("gobo.1.rotation", Beam, 1, 2),
        ("gobo.2", Beam, 1, 3),
        ("gobo.2.rotation", Beam, 1, 4),
        ("prism.1", Beam, 1, 5),
        ("prism.2", Beam, 1, 6),
        ("animation.1", Beam, 2, 1),
        ("prism.1.rotation", Beam, 2, 2),
        ("prism.2.rotation", Beam, 2, 3),
        ("animation.1.rotation", Beam, 2, 4),
        ("beam.effect.1", Beam, 2, 5),
        ("beam.effect.2", Beam, 2, 6),
        ("beam", Beam, 3, 1),
        ("iris", Shapers, 1, 1),
        ("shaper.blade.1.position", Shapers, 1, 2),
        ("shaper.blade.1.angle", Shapers, 1, 3),
        ("shaper.blade.2.position", Shapers, 1, 4),
        ("shaper.blade.2.angle", Shapers, 1, 5),
        ("shaper.rotation", Shapers, 1, 6),
        ("shaper.blade.3.position", Shapers, 2, 1),
        ("shaper.blade.3.angle", Shapers, 2, 2),
        ("shaper.blade.4.position", Shapers, 2, 3),
        ("shaper.blade.4.angle", Shapers, 2, 4),
        ("shaper.keystone.x", Shapers, 2, 5),
        ("shaper.keystone.y", Shapers, 2, 6),
        ("focus", Focus, 1, 1),
        ("zoom", Focus, 1, 2),
        ("softness", Focus, 1, 3),
        // Camera Zoom stays with the six pose encoders so its linked activation group never
        // crosses control surfaces. It is still classified as Focus in the attribute registry.
        ("camera.zoom", Position, 3, 1),
        ("control", Control, 1, 1),
        ("media.play_mode", Control, 1, 2),
        ("media.playback_speed", Control, 1, 3),
        ("media.playback_bpm", Control, 1, 4),
        ("media.scaling_mode", Control, 1, 5),
        ("media.folder", Media, 1, 1),
        ("media.file", Media, 1, 2),
        ("media.mask.folder", Media, 1, 3),
        ("media.mask.file", Media, 1, 4),
        ("audio.folder", Media, 2, 1),
        ("audio.file", Media, 2, 2),
        ("audio.transport", Media, 2, 3),
        ("audio.repeat", Media, 2, 4),
        ("audio.volume", Media, 2, 5),
        ("media.position.x", Media, 3, 1),
        ("media.position.y", Media, 3, 2),
        ("media.scale.x", Media, 3, 3),
        ("media.scale.y", Media, 3, 4),
        ("media.mask.invert", Media, 1, 5),
        ("media.mask.opacity", Intensity, 1, 3),
        ("media.effect.1", Media, 4, 1),
        ("media.effect.2", Media, 4, 2),
        ("media.effect.3", Media, 4, 3),
        ("media.effect.4", Media, 4, 4),
    ]
    .into_iter()
    .filter(|(id, _, _, _)| !built_in_attribute_is_retired(id))
    .map(|(id, group, page, slot)| AttributePlacement {
        attribute: AttributeKey(id.to_owned()),
        encoder: EncoderPlacement::new(group, page, slot),
        push_turn_of: match id {
            "color.wheel.1.rotation" => Some(AttributeKey("color.wheel.1".into())),
            "color.wheel.2.rotation" => Some(AttributeKey("color.wheel.2".into())),
            "prism.1.rotation" => Some(AttributeKey("prism.1".into())),
            "prism.2.rotation" => Some(AttributeKey("prism.2".into())),
            "animation.1.rotation" => Some(AttributeKey("animation.1".into())),
            _ => None,
        },
    })
    .collect()
}
