use super::*;

/// Built-in attribute registry. Custom attributes remain valid and use their persisted identifier
/// as the operator label until a desk extension supplies richer metadata.
pub const ATTRIBUTE_REGISTRY: &[AttributeDescriptor] = &[
    continuous(
        "intensity",
        "Intensity",
        AttributeClass::Intensity,
        "percent",
    ),
    indexed("shutter", "Shutter / Strobe", AttributeClass::Intensity),
    continuous("strobe", "Strobe", AttributeClass::Intensity, "hz"),
    continuous("volume", "Volume", AttributeClass::Intensity, "percent"),
    color("color", "Color", AttributeClass::Color),
    continuous("color.red", "Red", AttributeClass::Color, "percent"),
    continuous("color.green", "Green", AttributeClass::Color, "percent"),
    continuous("color.blue", "Blue", AttributeClass::Color, "percent"),
    continuous("color.cyan", "Cyan", AttributeClass::Color, "percent"),
    continuous("color.magenta", "Magenta", AttributeClass::Color, "percent"),
    continuous("color.yellow", "Yellow", AttributeClass::Color, "percent"),
    continuous("color.amber", "Amber", AttributeClass::Color, "percent"),
    continuous("color.white", "White", AttributeClass::Color, "percent"),
    continuous("color.uv", "UV", AttributeClass::Color, "percent"),
    continuous(
        "color.cold_white",
        "Cold White",
        AttributeClass::Color,
        "percent",
    ),
    continuous(
        "color.warm_white",
        "Warm White",
        AttributeClass::Color,
        "percent",
    ),
    continuous("color.lime", "Lime", AttributeClass::Color, "percent"),
    continuous("color.indigo", "Indigo", AttributeClass::Color, "percent"),
    continuous("color.mint", "Mint", AttributeClass::Color, "percent"),
    continuous(
        "color.temperature",
        "Color Temperature",
        AttributeClass::Color,
        "K",
    ),
    continuous("color.tint", "Tint", AttributeClass::Color, "percent"),
    projection_continuous("color.hue", "Hue", AttributeClass::Color, "deg"),
    projection_continuous(
        "color.saturation",
        "Saturation",
        AttributeClass::Color,
        "percent",
    ),
    projection_continuous(
        "color.brightness",
        "Color Brightness",
        AttributeClass::Color,
        "percent",
    ),
    indexed("color.wheel.1", "Color Wheel 1", AttributeClass::Color),
    continuous(
        "color.wheel.1.rotation",
        "Color Wheel 1 Rotation",
        AttributeClass::Color,
        "percent",
    ),
    indexed("color.wheel.2", "Color Wheel 2", AttributeClass::Color),
    continuous(
        "color.wheel.2.rotation",
        "Color Wheel 2 Rotation",
        AttributeClass::Color,
        "percent",
    ),
    continuous("pan", "Pan", AttributeClass::Position, "deg"),
    continuous("tilt", "Tilt", AttributeClass::Position, "deg"),
    continuous(
        "camera.position.x",
        "Camera X",
        AttributeClass::Position,
        "m",
    ),
    continuous(
        "camera.position.y",
        "Camera Y",
        AttributeClass::Position,
        "m",
    ),
    continuous(
        "camera.position.z",
        "Camera Z",
        AttributeClass::Position,
        "m",
    ),
    cyclic_continuous("camera.yaw", "Camera Yaw", AttributeClass::Position, "deg"),
    cyclic_continuous(
        "camera.pitch",
        "Camera Pitch",
        AttributeClass::Position,
        "deg",
    ),
    cyclic_continuous(
        "camera.roll",
        "Camera Roll",
        AttributeClass::Position,
        "deg",
    ),
    continuous("point.position.x", "Point X", AttributeClass::Position, "m"),
    continuous("point.position.y", "Point Y", AttributeClass::Position, "m"),
    continuous("point.position.z", "Point Z", AttributeClass::Position, "m"),
    cyclic_continuous(
        "point.rotation.x",
        "Point Rot X",
        AttributeClass::Position,
        "deg",
    ),
    cyclic_continuous(
        "point.rotation.y",
        "Point Rot Y",
        AttributeClass::Position,
        "deg",
    ),
    cyclic_continuous(
        "point.rotation.z",
        "Point Rot Z",
        AttributeClass::Position,
        "deg",
    ),
    continuous(
        "pan.continuous",
        "Continuous Pan",
        AttributeClass::Position,
        "percent",
    ),
    continuous(
        "tilt.continuous",
        "Continuous Tilt",
        AttributeClass::Position,
        "percent",
    ),
    continuous("pan.time", "Pan Time", AttributeClass::Position, "s"),
    continuous("tilt.time", "Tilt Time", AttributeClass::Position, "s"),
    continuous(
        "position.time",
        "Pan/Tilt Time",
        AttributeClass::Position,
        "s",
    ),
    continuous(
        "position.speed",
        "Position Speed",
        AttributeClass::Position,
        "percent",
    ),
    indexed("position.mode", "Position Mode", AttributeClass::Position),
    continuous(
        "position.movement",
        "Position Movement",
        AttributeClass::Position,
        "percent",
    ),
    cyclic_continuous(
        "position.rotation",
        "Head Rotation",
        AttributeClass::Position,
        "deg",
    ),
    indexed("gobo.1", "Gobo 1", AttributeClass::Beam),
    continuous(
        "gobo.1.rotation",
        "Gobo 1 Rotation",
        AttributeClass::Beam,
        "percent",
    ),
    indexed("gobo.2", "Gobo 2", AttributeClass::Beam),
    continuous(
        "gobo.2.rotation",
        "Gobo 2 Rotation",
        AttributeClass::Beam,
        "percent",
    ),
    indexed("prism.1", "Prism 1", AttributeClass::Beam),
    continuous(
        "prism.1.rotation",
        "Prism 1 Rotation",
        AttributeClass::Beam,
        "percent",
    ),
    indexed("prism.2", "Prism 2", AttributeClass::Beam),
    continuous(
        "prism.2.rotation",
        "Prism 2 Rotation",
        AttributeClass::Beam,
        "percent",
    ),
    indexed("animation.1", "Animation Wheel 1", AttributeClass::Beam),
    continuous(
        "animation.1.rotation",
        "Animation Rotation 1",
        AttributeClass::Beam,
        "percent",
    ),
    indexed("beam.effect.1", "Beam Effect 1", AttributeClass::Beam),
    indexed("beam.effect.2", "Beam Effect 2", AttributeClass::Beam),
    continuous("beam", "Beam", AttributeClass::Beam, "percent"),
    continuous("iris", "Iris", AttributeClass::Shapers, "percent"),
    continuous(
        "shaper.blade.1.position",
        "Blade 1 Position",
        AttributeClass::Shapers,
        "percent",
    ),
    continuous(
        "shaper.blade.1.angle",
        "Blade 1 Angle",
        AttributeClass::Shapers,
        "deg",
    ),
    continuous(
        "shaper.blade.2.position",
        "Blade 2 Position",
        AttributeClass::Shapers,
        "percent",
    ),
    continuous(
        "shaper.blade.2.angle",
        "Blade 2 Angle",
        AttributeClass::Shapers,
        "deg",
    ),
    cyclic_continuous(
        "shaper.rotation",
        "Shaper Rotation",
        AttributeClass::Shapers,
        "deg",
    ),
    continuous(
        "shaper.blade.3.position",
        "Blade 3 Position",
        AttributeClass::Shapers,
        "percent",
    ),
    continuous(
        "shaper.blade.3.angle",
        "Blade 3 Angle",
        AttributeClass::Shapers,
        "deg",
    ),
    continuous(
        "shaper.blade.4.position",
        "Blade 4 Position",
        AttributeClass::Shapers,
        "percent",
    ),
    continuous(
        "shaper.blade.4.angle",
        "Blade 4 Angle",
        AttributeClass::Shapers,
        "deg",
    ),
    continuous(
        "shaper.keystone.x",
        "Keystone X",
        AttributeClass::Shapers,
        "percent",
    ),
    continuous(
        "shaper.keystone.y",
        "Keystone Y",
        AttributeClass::Shapers,
        "percent",
    ),
    continuous("focus", "Focus", AttributeClass::Focus, "percent"),
    continuous("zoom", "Zoom", AttributeClass::Focus, "deg"),
    continuous("camera.zoom", "Camera Zoom", AttributeClass::Focus, "mm"),
    continuous("softness", "Softness", AttributeClass::Focus, "percent"),
    continuous("frost.1", "Frost 1", AttributeClass::Focus, "percent"),
    continuous("frost.2", "Frost 2", AttributeClass::Focus, "percent"),
    continuous("beam.edge", "Beam Edge", AttributeClass::Focus, "percent"),
    indexed("control.mode", "Fixture Mode", AttributeClass::Control),
    continuous(
        "control.speed",
        "Fixture Control Speed",
        AttributeClass::Control,
        "percent",
    ),
    control("control", "Control", AttributeClass::Control),
    indexed("media.folder", "Media Folder", AttributeClass::Media),
    indexed("media.file", "Media File", AttributeClass::Media),
    indexed("media.mask.folder", "Mask Folder", AttributeClass::Media),
    indexed("media.mask.file", "Mask File", AttributeClass::Media),
    indexed("audio.folder", "Audio Folder", AttributeClass::Media),
    indexed("audio.file", "Audio File", AttributeClass::Media),
    indexed("audio.transport", "Audio Transport", AttributeClass::Media),
    indexed("audio.repeat", "Audio Repeat", AttributeClass::Media),
    continuous(
        "audio.volume",
        "Audio Volume",
        AttributeClass::Media,
        "percent",
    ),
    continuous(
        "media.opacity",
        "Layer Opacity",
        AttributeClass::Media,
        "percent",
    ),
    color("media.tint", "Layer Tint", AttributeClass::Media),
    indexed("media.play_mode", "Play Mode", AttributeClass::Media),
    continuous(
        "media.playback_speed",
        "Playback Speed",
        AttributeClass::Media,
        "percent",
    ),
    continuous(
        "media.playback_bpm",
        "Playback BPM",
        AttributeClass::Media,
        "bpm",
    ),
    continuous(
        "media.playback.blur",
        "Blur",
        AttributeClass::Media,
        "percent",
    ),
    continuous(
        "media.grayscale",
        "Grayscale",
        AttributeClass::Media,
        "percent",
    ),
    indexed("media.scaling_mode", "Scaling Mode", AttributeClass::Media),
    cyclic_continuous(
        "media.rotation",
        "Layer Rotation",
        AttributeClass::Media,
        "deg",
    ),
    continuous(
        "media.position.x",
        "Position X",
        AttributeClass::Media,
        "percent",
    ),
    continuous(
        "media.position.y",
        "Position Y",
        AttributeClass::Media,
        "percent",
    ),
    continuous("media.scale.x", "Scale X", AttributeClass::Media, "percent"),
    continuous("media.scale.y", "Scale Y", AttributeClass::Media, "percent"),
    continuous(
        "media.mask.position.x",
        "Mask Position X",
        AttributeClass::Media,
        "percent",
    ),
    continuous(
        "media.mask.position.y",
        "Mask Position Y",
        AttributeClass::Media,
        "percent",
    ),
    continuous(
        "media.mask.scale.x",
        "Mask Scale X",
        AttributeClass::Media,
        "percent",
    ),
    continuous(
        "media.mask.scale.y",
        "Mask Scale Y",
        AttributeClass::Media,
        "percent",
    ),
    continuous(
        "media.mask.opacity",
        "Mask Opacity",
        AttributeClass::Media,
        "percent",
    ),
    indexed("media.mask.invert", "Invert Mask", AttributeClass::Media),
    indexed("media.flip_mirror", "Flip / Mirror", AttributeClass::Media),
    indexed("media.effect.1", "Media Effect 1", AttributeClass::Media),
    indexed("media.effect.2", "Media Effect 2", AttributeClass::Media),
    indexed("media.effect.3", "Media Effect 3", AttributeClass::Media),
    indexed("media.effect.4", "Media Effect 4", AttributeClass::Media),
    // Fixture-specific control channels.
    //
    // Every shipped profile addresses these, and until they were registered each one fell back to
    // the custom descriptor: family Custom, so it sat in the Custom encoder group instead of
    // beside the attributes it belongs with. Registering them puts each one in its own family and
    // gives it an operator label.
    //
    // They are recordable, because they are things an operator programs. The three exceptions are
    // the channels whose whole purpose is striking or dousing a lamp and forcing a reset: a cue
    // that fired one of those on playback would be a hazard, so they stay Control and stay out of
    // cues.
    control("fixture.reset", "Reset", AttributeClass::Control),
    control(
        "fixture.lamp_control",
        "Lamp Control",
        AttributeClass::Control,
    ),
    control(
        "fixture.power_special_functions",
        "Power / Special Functions",
        AttributeClass::Control,
    ),
    indexed(
        "fixture.control",
        "Fixture Control",
        AttributeClass::Control,
    ),
    indexed(
        "fixture.special_control",
        "Special Control",
        AttributeClass::Control,
    ),
    indexed("fixture.function", "Function", AttributeClass::Control),
    indexed(
        "fixture.plus_7_control",
        "Plus 7 Control",
        AttributeClass::Control,
    ),
    indexed("fixture.programs", "Programs", AttributeClass::Control),
    indexed(
        "fixture.fan_control",
        "Fan Control",
        AttributeClass::Control,
    ),
    continuous(
        "fixture.auto_speed",
        "Auto Program Speed",
        AttributeClass::Control,
        "percent",
    ),
    indexed("fixture.unused_4", "Unused 4", AttributeClass::Control),
    indexed("fixture.unused_7", "Unused 7", AttributeClass::Control),
    indexed("fixture.unused_8", "Unused 8", AttributeClass::Control),
    continuous(
        "fixture.pan_tilt_speed",
        "Pan / Tilt Speed",
        AttributeClass::Position,
        "percent",
    ),
    continuous(
        "fixture.pan_tilt_speed_time",
        "Pan / Tilt Speed or Time",
        AttributeClass::Position,
        "percent",
    ),
    continuous(
        "fixture.pan_tilt_time",
        "Pan / Tilt Time",
        AttributeClass::Position,
        "percent",
    ),
    continuous(
        "fixture.mspeed",
        "M-Speed",
        AttributeClass::Position,
        "percent",
    ),
    indexed(
        "fixture.blackout_move",
        "Blackout While Moving",
        AttributeClass::Position,
    ),
    indexed(
        "fixture.colour_macros",
        "Colour Macros",
        AttributeClass::Color,
    ),
    indexed(
        "fixture.colour_mix_control",
        "Colour Mix Control",
        AttributeClass::Color,
    ),
    continuous("fixture.tint", "Tint", AttributeClass::Color, "percent"),
    indexed("fixture.blade_1", "Blade 1", AttributeClass::Shapers),
    indexed("fixture.blade_2", "Blade 2", AttributeClass::Shapers),
    indexed("fixture.blade_3", "Blade 3", AttributeClass::Shapers),
    indexed("fixture.blade_4", "Blade 4", AttributeClass::Shapers),
    indexed(
        "fixture.framing_macro",
        "Framing Macro",
        AttributeClass::Shapers,
    ),
    continuous(
        "fixture.framing_macro_speed",
        "Framing Macro Speed",
        AttributeClass::Shapers,
        "percent",
    ),
    indexed(
        "fixture.barndoor_macros",
        "Barndoor Macros",
        AttributeClass::Shapers,
    ),
    continuous(
        "fixture.barndoor_macro_speed",
        "Barndoor Macro Speed",
        AttributeClass::Shapers,
        "percent",
    ),
    cyclic_continuous(
        "fixture.barndoor_module_rotation",
        "Barndoor Module Rotation",
        AttributeClass::Shapers,
        "deg",
    ),
    indexed(
        "fixture.effect_animations",
        "Effect Animations",
        AttributeClass::Beam,
    ),
    indexed(
        "fixture.effect_wheel_position",
        "Effect Wheel Position",
        AttributeClass::Beam,
    ),
    continuous(
        "fixture.effect_wheel_rotation",
        "Effect Wheel Rotation",
        AttributeClass::Beam,
        "percent",
    ),
    indexed(
        "fixture.effects_movement",
        "Effects Movement",
        AttributeClass::Beam,
    ),
    continuous(
        "fixture.effects_speed",
        "Effects Speed",
        AttributeClass::Beam,
        "percent",
    ),
    continuous(
        "fixture.fx_crossfade",
        "Effect Crossfade",
        AttributeClass::Beam,
        "percent",
    ),
    indexed(
        "fixture.beam_fx_select",
        "Beam Effect",
        AttributeClass::Beam,
    ),
    indexed(
        "fixture.beam_fx_movement",
        "Beam Effect Movement",
        AttributeClass::Beam,
    ),
    continuous(
        "fixture.beam_rate",
        "Beam Rate",
        AttributeClass::Beam,
        "percent",
    ),
    continuous(
        "fixture.beam_duration",
        "Beam Duration",
        AttributeClass::Beam,
        "percent",
    ),
    continuous(
        "fixture.beam_time",
        "Beam Time",
        AttributeClass::Beam,
        "percent",
    ),
    indexed(
        "fixture.plate_fx_select",
        "Plate Effect",
        AttributeClass::Beam,
    ),
    indexed(
        "fixture.plate_fx_movement",
        "Plate Effect Movement",
        AttributeClass::Beam,
    ),
    continuous(
        "fixture.plate_flash_rate",
        "Plate Flash Rate",
        AttributeClass::Beam,
        "percent",
    ),
    continuous(
        "fixture.plate_flash_duration",
        "Plate Flash Duration",
        AttributeClass::Beam,
        "percent",
    ),
    continuous(
        "fixture.plate_pixel_master",
        "Plate Pixel Master",
        AttributeClass::Intensity,
        "percent",
    ),
    continuous(
        "fixture.plate_background_master",
        "Plate Background Master",
        AttributeClass::Intensity,
        "percent",
    ),
];
