import { useEffect, useMemo, useState } from "react";
import { useServer } from "../../api/ServerContext";
import type { FixtureDefinition, MultiPatchInstance, PatchedFixture } from "../../api/types";
import { useApp } from "../../state/AppContext";
import { SearchBar } from "../common/SearchBar";
import { ConsoleNumberField, ConsoleTextField, parsePatchAddress } from "../input/ConsoleFields";
import { conflicts, firstFreeAddress, fixtureRange, fixtureRanges, groupFixtureFamilies, incrementFixtureName } from "./patchUtils";
import { Button, NumberField, Select, TextInput } from "../common";
import { WindowHeader } from "../window-kit";

type EditKind = "number" | "name" | "address" | "location" | "rotation" | "mode" | null;

export function FixturePatchSetup({ onMedia }: { onMedia?: () => void } = {}) {
  const server = useServer(); const { state, dispatch } = useApp();
  const layers = [...server.patchLayers].sort((a,b) => a.body.order - b.body.order).map((item) => item.body);
  const [activeLayer, setActiveLayer] = useState("default"); const [selectedFixture, setSelectedFixture] = useState<string | null>(null);
  const [browserOpen, setBrowserOpen] = useState(false); const [placementOpen, setPlacementOpen] = useState(false);
  const [layerModal, setLayerModal] = useState<"add" | "select" | null>(null); const [layerName, setLayerName] = useState("");
  const [query, setQuery] = useState(""); const [submitted, setSubmitted] = useState(""); const [typeFilter, setTypeFilter] = useState(""); const [manufacturer, setManufacturer] = useState("");
  const [familyKey, setFamilyKey] = useState(""); const [definitionKey, setDefinitionKey] = useState("");
  const [draft, setDraft] = useState({ name: "Fixture 1", count: "1", patch: "1.1" }); const [status, setStatus] = useState(""); const [busy, setBusy] = useState(false);
  const [edit, setEdit] = useState<EditKind>(null); const [editText, setEditText] = useState(""); const [vector, setVector] = useState({x:0,y:0,z:0}); const [pending, setPending] = useState<Partial<PatchedFixture> | null>(null); const [blockedBy, setBlockedBy] = useState<PatchedFixture[]>([]);
  const [multipatchOpen, setMultipatchOpen] = useState(false); const [multipatchDraft, setMultipatchDraft] = useState<MultiPatchInstance[]>([]);
  const all = server.patch?.fixtures ?? []; const visible = all.filter((fixture) => activeLayer === "all" || (fixture.layer_id || "default") === activeLayer);
  const selected = all.find((fixture) => fixture.fixture_id === selectedFixture) ?? null;
  const selectedModeFamily = selected ? groupFixtureFamilies(server.fixtureLibrary).find((item) => item.manufacturer === selected.definition.manufacturer && item.name === (selected.definition.name || selected.definition.model)) ?? null : null;
  const types = useMemo(() => [...new Set(server.fixtureLibrary.map((item) => item.device_type || "other"))].sort(), [server.fixtureLibrary]);
  const filtered = useMemo(() => server.fixtureLibrary.filter((item) => { const needle = submitted.trim().toLowerCase(); return (!typeFilter || item.device_type === typeFilter) && (!manufacturer || item.manufacturer === manufacturer) && (!needle || `${item.manufacturer} ${item.name} ${item.model} ${item.mode} ${item.device_type}`.toLowerCase().includes(needle)); }), [server.fixtureLibrary, submitted, typeFilter, manufacturer]);
  const families = useMemo(() => groupFixtureFamilies(filtered), [filtered]); const manufacturers = useMemo(() => [...new Set(server.fixtureLibrary.map((item) => item.manufacturer))].sort(), [server.fixtureLibrary]);
  const family = families.find((item) => item.key === familyKey) ?? families[0] ?? null; const definition = server.fixtureLibrary.find((item) => `${item.id}:${item.revision}` === definitionKey) ?? family?.modes[0] ?? null;
  useEffect(() => { if (!family) return; if (!family.modes.some((item) => `${item.id}:${item.revision}` === definitionKey)) setDefinitionKey(`${family.modes[0].id}:${family.modes[0].revision}`); }, [family, definitionKey]);
  const chooseFamily = (key: string) => { const next = families.find((item) => item.key === key); if (!next) return; setFamilyKey(key); setDefinitionKey(`${next.modes[0].id}:${next.modes[0].revision}`); setDraft((current) => ({...current, name: next.name})); };
  const beginPlacement = () => { if (!definition) return; const universe = parsePatchAddress(draft.patch)?.universe ?? 1; const address = firstFreeAddress(all, universe, definition.footprint) ?? 1; setDraft((current) => ({ ...current, patch: `${universe}.${address}`, name: current.name || definition.name })); setStatus(""); setPlacementOpen(true); };
  const addBatch = async () => { if (!definition) return; const parsed = parsePatchAddress(draft.patch); if (!parsed) return setStatus("Enter a patch as universe.address, for example 1.101."); let remaining = Math.max(1, Number(draft.count) || 1), address = parsed.address, added = 0, lastId: string | null = null; setBusy(true); while (remaining > 0 && address + definition.footprint - 1 <= 512 && !conflicts(all, parsed.universe, address, definition.footprint).length) { lastId = await server.patchFixture({ name: incrementFixtureName(draft.name, added), definition, universe: parsed.universe, address, layer_id: activeLayer === "all" ? "default" : activeLayer }); if (!lastId) break; added++; remaining--; address += definition.footprint; } setBusy(false); if (lastId) { setSelectedFixture(lastId); void server.setSelection([lastId]); } if (!remaining) { setPlacementOpen(false); setBrowserOpen(false); setStatus(""); return; } const suggestion = firstFreeAddress(server.patch?.fixtures ?? all, parsed.universe, definition.footprint, address); setDraft((current) => ({...current, count: String(remaining), patch: `${parsed.universe}.${suggestion ?? 1}`})); setStatus(`${added} fixture${added === 1 ? "" : "s"} added. Choose where to patch the remaining ${remaining}.`); };
  const armEdit = (fixture: PatchedFixture, kind: Exclude<EditKind,null>) => { if (!state.patchSetArmed) return; setSelectedFixture(fixture.fixture_id); if (kind === "number") setEditText(String(fixture.fixture_number ?? "")); else if (kind === "name") setEditText(fixture.name || fixture.definition.name); else if (kind === "address") setEditText(fixture.universe && fixture.address ? `${fixture.universe}.${fixture.address}` : ""); else if (kind === "location" || kind === "rotation") setVector(fixture[kind] ?? {x:0,y:0,z:0}); else if (kind === "mode") { const fixtureFamily = groupFixtureFamilies(server.fixtureLibrary).find((item) => item.manufacturer === fixture.definition.manufacturer && item.name === (fixture.definition.name || fixture.definition.model)); if (fixtureFamily) { setFamilyKey(fixtureFamily.key); setDefinitionKey(`${fixture.definition.id}:${fixture.definition.revision}`); } } setEdit(kind); };
  const applyEdit = async (changes: Partial<PatchedFixture>) => { if (!selected) return; if (changes.universe && changes.address) { const footprint = changes.definition?.footprint ?? selected.definition.footprint; const found = conflicts(all, changes.universe, changes.address, footprint, selected.fixture_id); if (found.length) { setPending(changes); setBlockedBy(found); return; } } if (await server.updatePatchedFixture(selected.fixture_id, changes)) { setEdit(null); dispatch({type:"SET_PATCH_ARMED",value:false}); } };
  const saveEdit = (value = editText) => { if (!selected) return; if (edit === "number") { const number = Number(value); if (Number.isInteger(number) && number > 0 && !all.some((fixture) => fixture.fixture_id !== selected.fixture_id && fixture.fixture_number === number)) void applyEdit({fixture_number:number}); } if (edit === "name") void applyEdit({name: value.trim() || selected.name}); if (edit === "address") { const parsed = parsePatchAddress(value); if (parsed) void applyEdit(parsed); else if (!value.trim()) void applyEdit({universe:null,address:null}); } if (edit === "location" || edit === "rotation") void applyEdit({[edit]: vector}); if (edit === "mode" && definition) void applyEdit({definition}); };
  const cancelEdit = () => { setEdit(null); setPending(null); setBlockedBy([]); dispatch({type:"SET_PATCH_ARMED",value:false}); };
  const createLayer = async (value = layerName) => { const name = value.trim(); if (!name) return; const id = crypto.randomUUID(); if (await server.savePatchLayer({id,name,order:layers.length})) { setActiveLayer(id); setLayerName(""); setLayerModal(null); } };
  const selectLayer = async (layerId: string) => { if (selected && await server.updatePatchedFixture(selected.fixture_id,{layer_id:layerId})) { setLayerModal(null); dispatch({type:"SET_PATCH_ARMED",value:false}); } };
  const openMultipatch = (fixture: PatchedFixture) => { setSelectedFixture(fixture.fixture_id); setMultipatchDraft(structuredClone(fixture.multipatch ?? [])); setMultipatchOpen(true); };
  const addMultipatch = () => setMultipatchDraft((current) => [...current, { id: crypto.randomUUID(), name: `Instance ${current.length + 2}`, universe: null, address: null, location: {x:0,y:0,z:0}, rotation: {x:0,y:0,z:0} }]);
  const updateMultipatch = (id: string, changes: Partial<MultiPatchInstance>) => setMultipatchDraft((current) => current.map((instance) => instance.id === id ? {...instance,...changes} : instance));
  const saveMultipatch = async () => { if (!selected) return; if (await server.updatePatchedFixture(selected.fixture_id, { multipatch: multipatchDraft })) setMultipatchOpen(false); };
  const setFixtureNumber = async (fixture: PatchedFixture) => { const value = window.prompt("Fixture ID", String(fixture.fixture_number ?? "")); if (value == null) return; const number = Number(value); if (!Number.isInteger(number) || number < 1) return void window.alert("Fixture IDs must be positive whole numbers."); if (all.some((candidate) => candidate.fixture_id !== fixture.fixture_id && candidate.fixture_number === number)) return void window.alert(`Fixture ID ${number} is already in use.`); if (await server.updatePatchedFixture(fixture.fixture_id,{fixture_number:number})) dispatch({type:"SET_PATCH_ARMED",value:false}); };
  const shownUniverse = parsePatchAddress(draft.patch)?.universe ?? 1; const shownAddress = parsePatchAddress(draft.patch)?.address ?? 0;
  return <div className={`show-patch-layout ${layerModal === "select" ? "layer-selecting" : ""}`}>
    <WindowHeader title="Show Patch" info={{ primary: `${all.length} fixtures · ${layers.length} layers`, secondary: server.unresolvedMvrFixtures.length ? `${server.unresolvedMvrFixtures.length} unresolved MVR fixtures excluded from output` : undefined }} actions={[[...(onMedia ? [{ id: "fixtures", label: "Fixtures", active: true, onClick: () => undefined },{ id: "media", label: "Media Servers", onClick: onMedia }] : [])],[...(selected && state.patchSetArmed ? [{ id: "fixture-number", label: "Set fixture ID", onClick: () => void setFixtureNumber(selected) }] : []),{ id: "layer", label: "+ Add layer", onClick: () => setLayerModal("add") },{ id: "fixture", label: "+ Add fixture", onClick: () => setBrowserOpen(true) }]]} />
    <aside className="patch-layers"><h3>{layerModal === "select" ? "Select layer" : "Layers"}</h3><Button className={activeLayer === "all" ? "active" : ""} onClick={() => layerModal === "select" ? undefined : setActiveLayer("all")}><b>All fixtures</b><span>{all.length}</span></Button>{layers.map((layer) => <Button key={layer.id} className={activeLayer === layer.id ? "active" : ""} onClick={() => layerModal === "select" ? void selectLayer(layer.id) : setActiveLayer(layer.id)}><b>{layer.name}</b><span>{all.filter((fixture) => (fixture.layer_id || "default") === layer.id).length}</span></Button>)}</aside>
    <section className="patch-table-wrap"><table className="patch-table"><thead><tr><th>Fixture ID</th><th>Name</th><th>Manufacturer</th><th>Type</th><th>Product / mode</th><th>Patch</th><th>Multi-patch</th><th>Location X/Y/Z</th><th>Rotation X/Y/Z</th><th>Layer</th></tr></thead><tbody>{visible.map((fixture,index) => <tr key={fixture.fixture_id} className={selectedFixture === fixture.fixture_id ? "selected" : ""} onClick={() => { setSelectedFixture(fixture.fixture_id); if (!state.patchSetArmed) void server.setSelection([fixture.fixture_id]); }}><td>{fixture.fixture_number ?? index+1}</td><td><Button className="patch-value" onClick={() => armEdit(fixture,"name")}>{fixture.name || fixture.definition.name}</Button></td><td>{fixture.definition.manufacturer}</td><td>{fixture.definition.device_type}</td><td><Button className="patch-value" onClick={() => armEdit(fixture,"mode")}>{fixture.definition.model} · {fixture.definition.mode}</Button></td><td><Button className="patch-address" onClick={() => armEdit(fixture,"address")}>{fixture.universe && fixture.address ? `${fixture.universe}.${fixture.address}` : "Unpatched"}</Button></td><td><Button className="patch-value" onClick={() => openMultipatch(fixture)}>{1 + (fixture.multipatch?.length ?? 0)} model{fixture.multipatch?.length ? "s" : ""}</Button></td><td><Button className="patch-value" onClick={() => armEdit(fixture,"location")}>{(["x","y","z"] as const).map((axis) => ((fixture.location?.[axis] ?? 0)/1000).toFixed(3)).join(" / ")} m</Button></td><td><Button className="patch-value" onClick={() => armEdit(fixture,"rotation")}>{Object.values(fixture.rotation ?? {x:0,y:0,z:0}).join("° / ")}°</Button></td><td><Button className="patch-value" onClick={() => { if (state.patchSetArmed) { setSelectedFixture(fixture.fixture_id); setLayerModal("select"); } }}>{layers.find((layer) => layer.id === (fixture.layer_id || "default"))?.name ?? "Default"}</Button></td></tr>)}</tbody></table>{!visible.length && <div className="patch-empty">No fixtures in this layer.</div>}</section>
    {browserOpen && <div className="stacked-modal-layer"><section className="nested-modal fixture-browser-modal"><header><h2>Add fixture</h2><Button onClick={() => setBrowserOpen(false)}>×</Button></header><SearchBar value={query} onChange={setQuery} onSearch={() => setSubmitted(query)} filters={[{id:"type",label:"Fixture type",options:types}]} values={{type:typeFilter}} onFilterChange={(_,value) => setTypeFilter(value)} placeholder="Search manufacturer, fixture, mode, or type"/><div className="fixture-picker-columns"><section><h3>Manufacturer</h3><Button className={!manufacturer ? "active":""} onClick={() => setManufacturer("")}>All manufacturers</Button>{manufacturers.map((name) => <Button className={manufacturer===name?"active":""} key={name} onClick={() => setManufacturer(name)}>{name}</Button>)}</section><section><h3>Fixture</h3>{families.map((item) => <Button className={family?.key===item.key?"active":""} key={item.key} onClick={() => chooseFamily(item.key)}>{item.name}<small>{item.deviceType} · {item.modes.length} modes</small></Button>)}</section><section className="fixture-mode-detail">{family && definition ? <><h3>{family.manufacturer} {family.name}</h3><label>Mode<Select value={`${definition.id}:${definition.revision}`} onChange={(event) => setDefinitionKey(event.target.value)}>{family.modes.map((mode) => <option value={`${mode.id}:${mode.revision}`} key={`${mode.id}:${mode.revision}`}>{mode.mode} · {mode.footprint}ch</option>)}</Select></label><FixtureDetails definition={definition}/><Button className="primary" onClick={beginPlacement}>Add fixture</Button></>:<p>Select a fixture.</p>}</section></div></section></div>}
    {placementOpen && definition && <div className="stacked-modal-layer"><section className="nested-modal fixture-placement-modal"><header><h2>Patch {family?.name}</h2><Button onClick={() => setPlacementOpen(false)}>×</Button></header><div className="placement-grid"><div className="placement-fields"><label>Mode<Select value={`${definition.id}:${definition.revision}`} onChange={(event) => setDefinitionKey(event.target.value)}>{family?.modes.map((mode) => <option value={`${mode.id}:${mode.revision}`} key={`${mode.id}:${mode.revision}`}>{mode.mode} · {mode.footprint}ch</option>)}</Select></label><label>Fixture name<ConsoleTextField autoFocus value={draft.name} onChange={(name) => setDraft({...draft,name})}/></label><small>Trailing numbers increment automatically.</small><label>Count<ConsoleNumberField value={draft.count} onChange={(count) => setDraft({...draft,count})}/></label><label>Address (universe.address)<ConsoleTextField value={draft.patch} onChange={(patch) => setDraft({...draft,patch})}/></label>{status && <p className="patch-status">{status}</p>}</div><UniverseMap fixtures={all} universe={shownUniverse} proposed={shownAddress} footprint={definition.footprint} onUniverse={(universe) => setDraft({...draft,patch:`${universe}.${firstFreeAddress(all,universe,definition.footprint) ?? 1}`})}/></div><footer><Button onClick={() => setPlacementOpen(false)}>Cancel</Button><Button className="primary" disabled={busy || !parsePatchAddress(draft.patch)} onClick={() => void addBatch()}>{busy?"Adding…":`Add ${draft.count || 1} fixtures`}</Button></footer></section></div>}
    {multipatchOpen && selected && <div className="stacked-modal-layer"><section className="nested-modal multipatch-modal"><header><div><h2>Multi-patch · {selected.name || selected.definition.name}</h2><small>All models share fixture and head IDs. Use 0 for visualizer-only.</small></div><Button onClick={() => setMultipatchOpen(false)}>×</Button></header><div className="multipatch-list"><article className="multipatch-primary"><b>Primary model</b><span>{selected.universe && selected.address ? `${selected.universe}.${selected.address}` : "0 · Visualizer only"}</span></article>{multipatchDraft.map((instance,index) => <article key={instance.id}><TextInput clearable aria-label={`Instance ${index+2} name`} value={instance.name} onChange={(event) => updateMultipatch(instance.id,{name:event.target.value})}/><TextInput aria-label={`Instance ${index+2} patch`} defaultValue={instance.universe && instance.address ? `${instance.universe}.${instance.address}` : "0"} onBlur={(event) => { const value=event.target.value.trim(); const parsed=parsePatchAddress(value); if (value==="0" || value==="") updateMultipatch(instance.id,{universe:null,address:null}); else if (parsed) updateMultipatch(instance.id,parsed); else event.target.value=instance.universe&&instance.address?`${instance.universe}.${instance.address}`:"0"; }}/>{(["x","y","z"] as const).map((axis)=><NumberField key={axis} label={`${axis.toUpperCase()} m`} allowDecimal step="0.1" value={instance.location[axis]/1000} onChange={(event)=>updateMultipatch(instance.id,{location:{...instance.location,[axis]:Math.round(Number(event.target.value)*1000)}})}/>)}{(["x","y","z"] as const).map((axis)=><NumberField key={`r${axis}`} label={`R${axis.toUpperCase()}°`} step="1" value={instance.rotation[axis]} onChange={(event)=>updateMultipatch(instance.id,{rotation:{...instance.rotation,[axis]:Number(event.target.value)}})}/>)}<Button className="danger" onClick={()=>setMultipatchDraft((current)=>current.filter((item)=>item.id!==instance.id))}>Remove</Button></article>)}</div><footer><Button onClick={addMultipatch}>+ Add model</Button><span className="spacer"/><Button onClick={()=>setMultipatchOpen(false)}>Cancel</Button><Button className="primary" onClick={()=>void saveMultipatch()}>Save multi-patch</Button></footer></section></div>}
    {layerModal === "add" && <div className="stacked-modal-layer"><section className="nested-modal patch-small-modal"><h3>Add layer</h3><TextInput clearable autoFocus aria-label="Layer name" value={layerName} onChange={(event) => setLayerName(event.target.value)} onKeyboardCommit={(value) => void createLayer(value)}/><footer><Button onClick={() => setLayerModal(null)}>Cancel</Button><Button onClick={() => void createLayer()}>Add layer</Button></footer></section></div>}
    {edit && selected && <div className="stacked-modal-layer"><section className="nested-modal patch-edit-modal"><h3>Set fixture {edit}</h3>{edit === "name" && <TextInput clearable autoFocus aria-label="Fixture name" value={editText} onChange={(event) => setEditText(event.target.value)} onKeyboardCommit={saveEdit}/>} {edit === "address" && <TextInput clearable autoFocus aria-label="Fixture address" placeholder="universe.address or blank to unpatch" value={editText} onChange={(event) => setEditText(event.target.value)} onKeyboardCommit={saveEdit}/>} {(edit === "location" || edit === "rotation") && <div className="vector-inputs">{(["x","y","z"] as const).map((axis) => <NumberField label={`${axis.toUpperCase()} ${edit === "location" ? "(m)" : ""}`} allowDecimal value={edit === "location" ? vector[axis]/1000 : vector[axis]} onChange={(event) => setVector({...vector,[axis]:edit === "location" ? Math.round(Number(event.target.value)*1000) : Number(event.target.value)})}/>)}</div>}{edit === "mode" && selectedModeFamily && <label>Product / mode<Select value={definitionKey} onChange={(event) => setDefinitionKey(event.target.value)}>{selectedModeFamily.modes.map((mode) => <option value={`${mode.id}:${mode.revision}`} key={`${mode.id}:${mode.revision}`}>{mode.mode} · {mode.footprint}ch</option>)}</Select></label>}<footer><Button onClick={cancelEdit}>Cancel</Button><Button onClick={() => saveEdit()}>Set</Button></footer></section></div>}
    {pending && selected && <div className="stacked-modal-layer"><section className="nested-modal conflict-modal"><h3>Patch conflict</h3><p>The requested range overlaps {blockedBy.map((fixture) => `${fixture.name || fixture.definition.name} (${fixtureRange(fixture)?.universe}.${fixtureRange(fixture)?.start}–${fixtureRange(fixture)?.end})`).join(", ")}.</p><footer><Button onClick={() => {setPending(null);setBlockedBy([]);}}>Keep old patch / mode</Button><Button onClick={() => void server.updatePatchedFixture(selected.fixture_id,{universe:null,address:null}).then(cancelEdit)}>Unpatch current fixture</Button><Button className="danger" onClick={() => { if (!window.confirm("Unpatch the conflicting fixtures and apply this change?")) return; void Promise.all(blockedBy.map((fixture) => server.updatePatchedFixture(fixture.fixture_id,{universe:null,address:null}))).then(() => applyEdit(pending)); }}>Unpatch conflicts and apply</Button></footer></section></div>}
  </div>;
}

function FixtureDetails({definition}:{definition:FixtureDefinition}) { return <div className="fixture-details"><strong>{definition.footprint} DMX channels</strong><span>{definition.device_type}</span><span>{definition.heads.length} head{definition.heads.length===1?"":"s"}</span><span>Revision {definition.revision}</span>{definition.physical.width_millimetres && <span>{definition.physical.width_millimetres} × {definition.physical.height_millimetres ?? "?"} × {definition.physical.depth_millimetres ?? "?"} mm</span>}</div>; }
function UniverseMap({fixtures,universe,proposed,footprint,onUniverse}:{fixtures:PatchedFixture[];universe:number;proposed:number;footprint:number;onUniverse:(universe:number)=>void}) { const ranges=fixtures.flatMap((fixture)=>fixtureRanges(fixture).map((range,index)=>({fixture,range,index}))).filter((item)=>item.range.universe===universe); return <section className="universe-visual"><header><h3>Universe {universe}</h3><Select value={universe} onChange={(event)=>onUniverse(Number(event.target.value))}>{Array.from({length:32},(_,index)=><option key={index+1}>{index+1}</option>)}</Select></header><div className="universe-range-list">{ranges.map(({fixture,range,index})=><div className="used-range" key={`${fixture.fixture_id}-${index}`} style={{top:`${((range.start-1)/512)*100}%`,height:`${Math.max(1,(fixture.definition.footprint/512)*100)}%`}}><b>{range.start}–{range.end}</b><span>{fixture.name || fixture.definition.name}{index ? ` · MP${index}` : ""}</span></div>)}{proposed>0&&<div className="proposed-range" style={{top:`${((proposed-1)/512)*100}%`,height:`${Math.max(1,(footprint/512)*100)}%`}}>{proposed}–{proposed+footprint-1}</div>}</div></section>; }
