import { describe, expect, it } from "vitest";
import type { FixtureDefinition, PatchedFixture } from "../../api/types";
import { compareFixtureManufacturers, compatibleHighlightOverrides, conflicts, firstFreeAddress, groupFixtureFamilies, incrementFixtureName, isDmxPatchable } from "./patchUtils";
import { parsePatchAddress } from "../input/ConsoleFields";
import { blankChannel, blankFixtureProfile } from "./fixtureProfileModel";

const definition = (footprint = 10, mode = "Standard"): FixtureDefinition => ({ schema_version:1,id:mode,revision:1,manufacturer:"Acme",device_type:"wash mover",name:"Beam",model:"Beam",mode,footprint,heads:[],color_calibration:null,physical:{},hazardous:false,direct_control_protocols:[],signal_loss_policy:{type:"hold_last"},safe_values:{} });
const fixture = (id:string,address:number|null,footprint=10): PatchedFixture => ({fixture_id:id,name:id,universe:address == null ? null : 1,address,layer_id:"default",definition:definition(footprint),logical_heads:[]});

describe("patch utilities", () => {
  it("parses the single universe.address field", () => { expect(parsePatchAddress("2.101")).toEqual({universe:2,address:101}); expect(parsePatchAddress("2")).toBeNull(); expect(parsePatchAddress("1.513")).toBeNull(); });
  it("increments trailing fixture numbers", () => { expect(incrementFixtureName("Wash 07",2)).toBe("Wash 9"); expect(incrementFixtureName("Wash",1)).toBe("Wash 2"); });
  it("ignores unpatched fixtures and finds exact free boundaries", () => { const fixtures=[fixture("one",1),fixture("unpatched",null),fixture("two",21)]; expect(conflicts(fixtures,1,10,2)).toHaveLength(1); expect(firstFreeAddress(fixtures,1,10)).toBe(11); expect(firstFreeAddress([fixture("edge",503,10)],1,10,503)).toBeNull(); });
  it("reserves patched multi-patch ranges but ignores visualizer-only models", () => { const multi=fixture("multi",1,3); multi.multipatch=[{id:"output",name:"Output",universe:1,address:20,location:{x:0,y:0,z:0},rotation:{x:0,y:0,z:0}},{id:"visual",name:"Visual",universe:null,address:null,location:{x:0,y:0,z:0},rotation:{x:0,y:0,z:0}}]; expect(conflicts([multi],1,21,1)).toEqual([multi]); expect(conflicts([multi],1,30,1)).toEqual([]); });
  it("reserves every independently patched schema-v2 split and multi-patch split", () => { const split=fixture("split",null,4); const profile=blankFixtureProfile(); profile.modes[0].splits=[{number:1,footprint:4},{number:2,footprint:8}]; split.definition={...split.definition,schema_version:2,profile_id:profile.id,mode_id:profile.modes[0].id,profile_snapshot:profile}; split.split_patches=[{split:1,universe:1,address:10},{split:2,universe:2,address:100}]; split.multipatch=[{id:"mp",name:"mp",universe:null,address:null,split_patches:[{split:1,universe:null,address:null},{split:2,universe:3,address:200}],location:{x:0,y:0,z:0},rotation:{x:0,y:0,z:0}}]; expect(conflicts([split],2,107,1)).toEqual([split]); expect(conflicts([split],3,207,1)).toEqual([split]); expect(conflicts([split],2,108,1)).toEqual([]); });
  it("groups named modes into a fixture family", () => { const families=groupFixtureFamilies([definition(10,"A"),definition(20,"B")]); expect(families).toHaveLength(1); expect(families[0].modes.map((mode)=>mode.mode)).toEqual(["A","B"]); });
  it("pins Generic and Venue before real manufacturers and preserves authored mode order", () => { expect(["ROBE","Venue","Generic","ETC"].sort(compareFixtureManufacturers)).toEqual(["Generic","Venue","ETC","ROBE"]); const modes=[definition(1,"10 cm"),definition(1,"1 m")]; expect(groupFixtureFamilies(modes)[0].modes.map((mode)=>mode.mode)).toEqual(["10 cm","1 m"]); });
  it("recognizes a portable visual-only profile snapshot", () => { const profile=blankFixtureProfile(); profile.patch_policy="visual_only"; const visual={...definition(0),schema_version:2 as const,profile_snapshot:profile}; expect(isDmxPatchable(visual)).toBe(false); expect(isDmxPatchable(definition())).toBe(true); });
  it("retains only Highlight overrides compatible with a replacement mode", () => { const profile=blankFixtureProfile(); const channel={...blankChannel(profile.modes[0]),id:"shared",resolution:"u8" as const}; profile.modes[0].channels=[channel]; const replacement={...definition(1,"Replacement"),schema_version:2,profile_id:profile.id,mode_id:profile.modes[0].id,profile_snapshot:profile}; expect(compatibleHighlightOverrides(replacement,{shared:173,stale:20})).toEqual({shared:173}); expect(compatibleHighlightOverrides(replacement,{shared:256})).toEqual({}); });
});
