[package]
name = "light-engine"
version.workspace = true
edition.workspace = true
license-file.workspace = true

[dependencies]
arc-swap.workspace = true
chrono.workspace = true
light-core = { path = "../../../shared/core" }
light-control = { path = "../control", default-features = false }
light-dynamics = { path = "../dynamics" }
light-fixture = { path = "../../../shared/fixture" }
light-output = { path = "../output" }
light-playback = { path = "../playback" }
light-programmer = { path = "../programmer" }
parking_lot.workspace = true
serde.workspace = true
thiserror.workspace = true
uuid.workspace = true

[lints]
workspace = true
