import type { EffectType } from "../../shared/api/effects";

// Generated by media-render's effect_thumbnails example: real off-screen frames of each shipped
// preset through the program compositor, keyed by the library editor's effect type. They are
// static assets, so choosing an effect never renders anything on the server or blocks playback.
const thumbnailModules = import.meta.glob<string>("./thumbnails/*.png", {
	eager: true,
	query: "?url",
	import: "default",
});

const thumbnailsByType = new Map<string, string>();
for (const [path, url] of Object.entries(thumbnailModules)) {
	const match = /\/([a-z-]+)\.png$/u.exec(path);
	if (match?.[1]) thumbnailsByType.set(match[1], url);
}

/** The representative thumbnail for an effect type, or undefined for an unknown type. */
export function effectThumbnailUrl(
	type: EffectType | undefined,
): string | undefined {
	return type ? thumbnailsByType.get(type) : undefined;
}

export function effectThumbnailTypes(): string[] {
	return [...thumbnailsByType.keys()].sort();
}
