[package]
name = "viz-demo"
version.workspace = true
edition.workspace = true
license-file.workspace = true

[[bin]]
name = "viz-demo-show"
path = "src/bin/viz-demo-show.rs"

[dependencies]
light-fixture = { path = "../../shared/fixture" }
viz-document = { path = "../document" }

[lints]
workspace = true
