use light_core::{ATTRIBUTE_REGISTRY, AttributeConfiguration, EncoderGroup};
use std::{env, fs, path::Path};

fn encoder_group_label(group: EncoderGroup) -> &'static str {
    match group {
        EncoderGroup::Intensity => "Intensity",
        EncoderGroup::Color => "Color",
        EncoderGroup::Position => "Position",
        EncoderGroup::Beam => "Beam",
        EncoderGroup::Shapers => "Shapers",
        EncoderGroup::Focus => "Focus",
        EncoderGroup::Control => "Control",
        EncoderGroup::Media => "Media",
    }
}

fn label_for(id: &str) -> String {
    ATTRIBUTE_REGISTRY
        .iter()
        .find(|descriptor| descriptor.id == id)
        .map(|descriptor| descriptor.label.to_owned())
        .unwrap_or_else(|| id.to_owned())
}

fn attribute_reference(id: &str) -> String {
    format!("**{}** (`{id}`)", label_for(id))
}

fn main() {
    let output = env::args().nth(1).unwrap_or_else(|| {
        eprintln!("usage: generate_attribute_reference <output-path>");
        std::process::exit(2);
    });
    let configuration = AttributeConfiguration::recommended();
    let mut placements = configuration.placements;
    placements.sort_by_key(|placement| {
        (
            placement.encoder.group,
            placement.encoder.page,
            placement.encoder.slot,
        )
    });

    let mut document = String::from(
        "# Default Attribute Activation and Encoder Assignments\n\n> Generated from `AttributeConfiguration::recommended()` by `cargo run --package light-core --example generate_attribute_reference`. Do not edit this file by hand.\n\nThese are the defaults applied by **Restore recommended defaults**. A show may have a different layout or activation grouping.\n\n## Default encoder assignments\n\n| Encoder group | Encoder | Attribute | Push-turn companion |\n| --- | --- | --- | --- |\n",
    );
    for placement in placements {
        let push_turn = placement
            .push_turn_of
            .as_ref()
            .map(|attribute| attribute_reference(&attribute.0))
            .unwrap_or_else(|| "—".to_owned());
        document.push_str(&format!(
            "| {} | P{}/E{} | {} | {} |\n",
            encoder_group_label(placement.encoder.group),
            placement.encoder.page,
            placement.encoder.slot,
            attribute_reference(&placement.attribute.0),
            push_turn,
        ));
    }

    document.push_str(
        "\n## Default attribute activation groups\n\n| Group | Attributes activated together |\n| --- | --- |\n",
    );
    for group in configuration.activation_groups {
        let members = group
            .members
            .iter()
            .map(|attribute| attribute_reference(&attribute.0))
            .collect::<Vec<_>>()
            .join("<br>");
        document.push_str(&format!("| **{}** | {} |\n", group.label, members));
    }

    let output = Path::new(&output);
    if let Some(parent) = output.parent() {
        fs::create_dir_all(parent).expect("create generated reference directory");
    }
    fs::write(output, document).expect("write generated attribute reference");
}
