#!/usr/bin/env python3
"""Build the fixture, truss and stage models with Blender.

Run it through Blender, not through a bare Python interpreter::

    blender --background --factory-startup --python tools/build_stage_models.py -- \
        --output assets/models

Or through the npm script, which does the same thing::

    npm run models

Each model is written as a self-contained ``.glb`` under ``assets/models/<group>/``,
and ``assets/models/manifest.json`` records the size and node list a fixture profile
has to declare. What the files must satisfy is written down in
``docs/engineering/fixture-and-stage-model-brief.md``; ``tools/verify_stage_models.py``
checks the output against it.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
if str(ROOT / "tools") not in sys.path:
    sys.path.insert(0, str(ROOT / "tools"))

from stage_models import av, backline, cases, kit, lamps, people, stage, truss  # noqa: E402

DEFAULT_OUTPUT = ROOT / "assets" / "models"


def parse_args() -> argparse.Namespace:
    arguments = sys.argv[sys.argv.index("--") + 1 :] if "--" in sys.argv else []
    parser = argparse.ArgumentParser(prog="build_stage_models")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument(
        "--only",
        default="",
        help="build one group or one model by name, for iterating on a single lamp",
    )
    parser.add_argument(
        "--blend",
        type=Path,
        help="also save a .blend holding the whole set laid out, for looking at it",
    )
    return parser.parse_args(arguments)


def selected(only: str = "") -> list:
    models = [
        *lamps.models(),
        *truss.models(),
        *stage.models(),
        *av.models(),
        *cases.models(),
        *backline.models(),
        *people.models(),
    ]
    if only:
        models = [model for model in models if only in (model.name, model.group)]
        if not models:
            raise SystemExit(f"build error: nothing matches --only {only!r}")
    return models


def variants(models: list) -> list:
    """Each model, and — where it carries mounting hardware — the same model without it.

    A fixture is not always on the clamp it ships with: it goes on a floor base, on the
    venue's own bracket, or into a case. Both are written so a profile can point at the one
    it means, and both keep the same origin, so swapping one for the other in a rig moves
    nothing.
    """

    both = []
    for model in models:
        both.append(model)
        bare = kit.unrigged(model)
        if bare is not None:
            both.append(bare)
    return both


def build(output: Path, only: str = "") -> list[dict[str, object]]:
    models = variants(selected(only))
    entries: list[dict[str, object]] = []
    for index, model in enumerate(models, start=1):
        entry = kit.write(model, output)
        entries.append(entry)
        print(f"[{index}/{len(models)}] {entry['file']}: {entry['triangles']} triangles")
    return entries


def main() -> int:
    arguments = parse_args()
    entries = build(arguments.output, arguments.only)
    manifest = arguments.output / "manifest.json"
    existing = json.loads(manifest.read_text())["models"] if manifest.exists() else []
    kept = {entry["file"]: entry for entry in existing}
    kept.update({entry["file"]: entry for entry in entries})
    if not arguments.only:
        # A full build is the whole set by definition, so anything left over is a model
        # that was renamed or dropped. Left in place it would keep passing the verifier
        # off its stale manifest entry and keep shipping in the package.
        wanted = {str(entry["file"]) for entry in entries}
        for stale in sorted(set(kept) - wanted):
            kept.pop(stale)
            (arguments.output / stale).unlink(missing_ok=True)
            print(f"removed {stale}")
        for path in sorted(arguments.output.rglob("*.glb")):
            if path.relative_to(arguments.output).as_posix() not in wanted:
                path.unlink()
                print(f"removed {path.relative_to(arguments.output).as_posix()}")
    payload = {
        "note": (
            "Generated by tools/build_stage_models.py. Sizes are the model's own bounding box "
            "in millimetres, in the fixture profile's axes; copy them into width/height/depth so "
            "the visualizer's scale factor comes out at 1."
        ),
        "models": sorted(kept.values(), key=lambda entry: str(entry["file"])),
    }
    manifest.write_text(json.dumps(payload, indent=2) + "\n")
    print(f"wrote {len(entries)} models and {manifest}")
    if arguments.blend is not None:
        kit.write_review_file(variants(selected(arguments.only)), arguments.blend)
        print(f"wrote {arguments.blend}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
