"""Generate the Model Catalogue Markdown from the shipped model manifest."""

from __future__ import annotations

import json
from pathlib import Path

GROUP_TITLES = {
    "lamps": "Lamps",
    "truss": "Truss and rigging",
    "stage": "Stage and venue",
    "av": "Projection and laser",
    "cases": "Flight cases",
    "backline": "Backline and PA",
    "people": "Figures",
}
GROUP_ORDER = ("lamps", "av", "truss", "stage", "cases", "backline", "people")


def write_catalogue(models: Path, images: Path, page: Path) -> None:
    manifest = json.loads((models / "manifest.json").read_text())
    relative = Path("..") / images.relative_to(page.parent.parent)
    lines = [
        "# Model Catalogue",
        "",
        "<!-- toc: exclude-headings -->",
        "",
        "Every model ToskLight ships with the Visualizer, with the name the fixture",
        "library and the show file refer to it by. A fixture profile points at one of",
        "these with `model_asset`; a fixture that points at nothing is given one",
        "automatically, as described in [Default Models](../20-ToskLight-PreViz/01-default-models.md).",
        "",
        "This page is generated by `npm run models:render` from `assets/models`. Edit the",
        "builders under `tools/stage_models/`, not this file.",
        "",
    ]
    for group in GROUP_ORDER:
        members = [entry for entry in manifest["models"] if entry["group"] == group]
        if not members:
            continue
        pairs: dict[str, dict[str, dict]] = {}
        for entry in members:
            stem = Path(str(entry["file"])).stem
            pair = pairs.setdefault(stem.removesuffix("-no-clamp"), {})
            pair["regular" if stem.endswith("-no-clamp") else "clamped"] = entry

        lines.extend(
            [
                f"## {GROUP_TITLES.get(group, group.title())}",
                "",
                "| Model | With clamp | Name and description | Physical properties |",
                "| --- | --- | --- | --- |",
            ]
        )
        for base, pair in sorted(pairs.items()):
            regular = pair.get("regular") or pair.get("clamped")
            clamped = pair.get("clamped") if pair.get("regular") else None
            assert regular is not None

            def picture(entry: dict, label: str) -> str:
                name = Path(str(entry["file"])).stem
                return f"![{label}: {base}]({relative.as_posix()}/{group}/{name}.png)"

            def dimensions(entry: dict) -> str:
                return (
                    f"{entry['width_millimetres']:.0f} x {entry['height_millimetres']:.0f} x "
                    f"{entry['depth_millimetres']:.0f} mm"
                )

            description = str((clamped or regular)["summary"]).replace("; no mounting hardware", "")
            properties = f"**Model:** {dimensions(regular)}"
            if clamped:
                properties += f"<br>**With clamp:** {dimensions(clamped)}"
            lines.append(
                f"| {picture(regular, 'Model')} | "
                f"{picture(clamped, 'With clamp') if clamped else '—'} | "
                f"`{base}`<br>{description} | {properties} |"
            )
        lines.append("")
    page.parent.mkdir(parents=True, exist_ok=True)
    page.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
