import { initialDesks } from "../data/mockData";
import type { AppState } from "../types";

export const initialState: AppState = {
	dockMode: "desks",
	activeDeskId: "programming",
	desks: initialDesks,
	builtIn: null,
	lastBuiltIn: "stage",
	fileManagerReturn: null,
	controlMode: "programmer",
	paneSettingsId: null,
	maximizedPaneId: null,
	windowPicker: null,
	savingDesk: false,
	speedGroup: "A",
	playbackColumns: 8,
	playbackRows: 1,
	playbackPage: 0,
	playbackPageNames: Array.from({ length: 127 }, (_, index) =>
		index === 0 ? "Main" : `Page ${index + 1}`,
	),
	presetFamily: "Mixed",
	presetPoolColors: true,
	presetSetArmed: false,
	cuelistBuiltInView: "pool",
	cuelistBuiltInNumber: null,
	cueListSetArmed: false,
	cueListSetTarget: null,
	playbackSetArmed: false,
	setupOpen: false,
	specialDialogsOpen: false,
	specialDialogFamily: "Position",
	systemControlsOpen: false,
	preloadStoreOpen: false,
	storeArmed: false,
	updateArmed: false,
	shiftArmed: false,
	storeSettingsOpen: false,
	patchSetArmed: false,
	midiProfile: false,
	debugOpen: false,
	touchScrollbars: false,
	showSectionNames: false,
	regularNumberShortcuts: true,
	deskSettingsOpen: false,
	deskSettingsId: null,
	stageMode: "select",
	stageView: "2d",
	stageZoom: 1,
	stagePanX: 0,
	stagePanY: 0,
	stageOrbitX: 0,
	stageOrbitY: 0,
	stageGroupsVisible: true,
	stageShowSelection: true,
	stageShowFloorGrid: true,
	stageShowBeamGuides: true,
	stageEnvironmentBrightness: 1,
	dmxDotSize:
		typeof globalThis.matchMedia === "function" &&
		globalThis.matchMedia("(pointer: coarse)").matches
			? "large"
			: "small",
	fixtureSheetOrder: "fixture-id",
	fixtureSheetActiveOnly: false,
	fixtureSheetCueListId: "",
	fixtureSheetColumns: [
		"id",
		"icon",
		"name",
		"dimmer",
		"color",
		"position",
		"beam",
		"focus",
	],
	fixtureSheetShowType: true,
	fixtureSheetIncludedHeads: "all",
	fixtureGroupsVisible: true,
	presetGroupsVisible: true,
	groupsReturnToStage: null,
};
