import { Children, forwardRef, isValidElement, useEffect, useId, useImperativeHandle, useRef, useState, type ButtonHTMLAttributes, type ChangeEvent, type InputHTMLAttributes, type ReactNode, type SelectHTMLAttributes, type TextareaHTMLAttributes } from "react";
import { createPortal } from "react-dom";

export type ControlSize = "default" | "compact";
export type ButtonVariant = "primary" | "secondary" | "ghost" | "danger" | "success" | "warning";
export interface ButtonProps extends ButtonHTMLAttributes<HTMLButtonElement> { variant?: ButtonVariant; size?: ControlSize; active?: boolean; loading?: boolean; fullWidth?: boolean; iconOnly?: boolean }
export const Button = forwardRef<HTMLButtonElement,ButtonProps>(function Button({variant="secondary",size="default",active=false,loading=false,fullWidth=false,iconOnly=false,className="",disabled,children,type="button",...props},ref){return <button ref={ref} type={type} disabled={disabled||loading} aria-busy={loading||undefined} className={`ui-button ui-${variant} ui-${size} ${active?"is-active":""} ${fullWidth?"is-full-width":""} ${iconOnly?"is-icon-only":""} ${className}`.trim()} {...props}>{loading?<><span className="ui-spinner" aria-hidden="true"/>Loading</>:children}</button>});
const NumericInput=forwardRef<HTMLInputElement,InputHTMLAttributes<HTMLInputElement>>(function NumericInput({className="",value,defaultValue,onChange,disabled,readOnly,...props},ref){const [open,setOpen]=useState(false);const native=useRef<HTMLInputElement>(null);useImperativeHandle(ref,()=>native.current!);const current=String(value??defaultValue??"");const update=(next:string)=>{if(!native.current)return;const min=props.min==null?-Infinity:Number(props.min),max=props.max==null?Infinity:Number(props.max);const parsed=Number(next);native.current.value=next===""||next==="-"||next.endsWith(".")?next:String(Math.max(min,Math.min(max,parsed)));onChange?.({target:native.current,currentTarget:native.current} as ChangeEvent<HTMLInputElement>)};const press=(key:string)=>{if(key==="⌫")return update(current.slice(0,-1));if(key==="−")return update(current.startsWith("-")?current.slice(1):`-${current}`);if(key==="."&&!current.includes("."))return update(`${current||"0"}.`);if(/^\d$/.test(key))update(`${current}${key}`)};return <span className="ui-number-control"><input {...props} ref={native} type="number" value={value} defaultValue={defaultValue} onChange={onChange} disabled={disabled} readOnly={readOnly} className={`ui-input ${className}`.trim()}/><Button size="compact" iconOnly aria-label="Open number pad" disabled={disabled||readOnly} onClick={()=>setOpen(true)}>▦</Button>{open&&createPortal(<div className="ui-number-backdrop" onPointerDown={(event)=>event.target===event.currentTarget&&setOpen(false)}><section className="ui-number-modal" role="dialog" aria-modal="true" aria-label={props["aria-label"]??"Number input"}><header><strong>{current||"0"}</strong><Button size="compact" iconOnly aria-label="Close number pad" onClick={()=>setOpen(false)}>×</Button></header><div>{["7","8","9","4","5","6","1","2","3","−","0",".","⌫"].map((key)=><Button key={key} variant={key==="⌫"?"warning":"secondary"} onClick={()=>press(key)}>{key}</Button>)}<Button className="ui-number-enter" variant="primary" onClick={()=>setOpen(false)}>ENTER</Button></div></section></div>,document.body)}</span>});
export const Input=forwardRef<HTMLInputElement,InputHTMLAttributes<HTMLInputElement>>(function Input({className="",type="text",...props},ref){if(type==="number")return <NumericInput {...props} className={className} ref={ref}/>;const native=["checkbox","radio","range","file","color","hidden"].includes(type);return <input ref={ref} type={type} className={`${native?"ui-native-control":"ui-input"} ${className}`.trim()} {...props}/>});
export const Select=forwardRef<HTMLSelectElement,SelectHTMLAttributes<HTMLSelectElement>>(function Select({className="",children,value,defaultValue,onChange,disabled,"aria-label":ariaLabel,...props},ref){const native=useRef<HTMLSelectElement>(null);useImperativeHandle(ref,()=>native.current!);const options=Children.toArray(children).filter(isValidElement).map((child)=>{const option=child.props as {value?:string|number;children?:ReactNode;disabled?:boolean};const label=option.children;return {value:String(option.value??(typeof label==="string"||typeof label==="number"?label:"")),label,disabled:option.disabled}});const selected=String(value??defaultValue??options[0]?.value??"");return <><select {...props} ref={native} value={selected} onChange={onChange} disabled={disabled} className="ui-visually-hidden-select" aria-hidden="true" tabIndex={-1}>{children}</select><SelectField label={ariaLabel} className={className} value={selected} disabled={disabled} options={options} onChange={(next)=>{if(native.current)native.current.value=next;onChange?.({target:native.current,currentTarget:native.current} as ChangeEvent<HTMLSelectElement>)}}/></>});
export const TextArea=forwardRef<HTMLTextAreaElement,TextareaHTMLAttributes<HTMLTextAreaElement>>(function TextArea({className="",...props},ref){return <textarea ref={ref} className={`ui-textarea ${className}`.trim()} {...props}/>});

export function Field({label,description,error,required,htmlFor,children,className=""}:{label?:ReactNode;description?:ReactNode;error?:ReactNode;required?:boolean;htmlFor?:string;children:ReactNode;className?:string}){return <div className={`ui-field ${error?"has-error":""} ${className}`.trim()}>{label&&<label htmlFor={htmlFor}>{label}{required&&<span aria-hidden="true"> *</span>}</label>}{children}{description&&!error&&<small>{description}</small>}{error&&<small className="ui-field-error" role="alert">{error}</small>}</div>}

type TextProps=InputHTMLAttributes<HTMLInputElement>&{label?:ReactNode;description?:ReactNode;error?:ReactNode;controlSize?:ControlSize};
export const TextField=forwardRef<HTMLInputElement,TextProps>(function TextField({label,description,error,controlSize="default",id,className="",required,...props},ref){const generated=useId(),fieldId=id??generated,descriptionId=(description||error)?`${fieldId}-description`:undefined;return <Field label={label} description={description} error={error} required={required} htmlFor={fieldId}><input {...props} required={required} ref={ref} id={fieldId} aria-invalid={Boolean(error)||undefined} aria-describedby={descriptionId} className={`ui-input ui-${controlSize} ${className}`.trim()}/></Field>});
export const NumberField=forwardRef<HTMLInputElement,TextProps>(function NumberField({label,description,error,id,required,className="",...props},ref){const generated=useId(),fieldId=id??generated;return <Field label={label} description={description} error={error} required={required} htmlFor={fieldId}><NumericInput {...props} required={required} id={fieldId} className={className} inputMode={props.inputMode??"numeric"} ref={ref}/></Field>});
export const TextAreaField=forwardRef<HTMLTextAreaElement,TextareaHTMLAttributes<HTMLTextAreaElement>&{label?:ReactNode;description?:ReactNode;error?:ReactNode}>(function TextAreaField({label,description,error,id,className="",required,...props},ref){const generated=useId(),fieldId=id??generated;return <Field label={label} description={description} error={error} required={required} htmlFor={fieldId}><textarea {...props} required={required} ref={ref} id={fieldId} aria-invalid={Boolean(error)||undefined} className={`ui-textarea ${className}`.trim()}/></Field>});

export interface SelectOption<T extends string=string>{value:T;label:ReactNode;disabled?:boolean}
export function SelectField<T extends string>({label,value,options,onChange,description,error,disabled,size="default",className=""}:{label?:ReactNode;value:T;options:SelectOption<T>[];onChange:(value:T)=>void;description?:ReactNode;error?:ReactNode;disabled?:boolean;size?:ControlSize;className?:string}){const [open,setOpen]=useState(false),[active,setActive]=useState(()=>Math.max(0,options.findIndex((item)=>item.value===value)));const button=useRef<HTMLButtonElement>(null);useEffect(()=>{if(!open)return;const close=(event:KeyboardEvent)=>{if(event.key==="Escape"){event.preventDefault();setOpen(false);button.current?.focus();}if(event.key==="ArrowDown")setActive((index)=>Math.min(options.length-1,index+1));if(event.key==="ArrowUp")setActive((index)=>Math.max(0,index-1));if(event.key==="Enter"&&options[active]&&!options[active].disabled){onChange(options[active].value);setOpen(false);button.current?.focus();}};window.addEventListener("keydown",close,true);return()=>window.removeEventListener("keydown",close,true)},[open,active,options,onChange]);const chosen=options.find((item)=>item.value===value);return <Field label={label} description={description} error={error} className={className}><Button ref={button} className="ui-select-trigger" size={size} disabled={disabled} aria-haspopup="listbox" aria-expanded={open} onClick={()=>setOpen(!open)}><span>{chosen?.label??value}</span><i aria-hidden="true">▾</i></Button>{open&&createPortal(<div className="ui-select-backdrop" onPointerDown={(event)=>{if(event.target===event.currentTarget){setOpen(false);button.current?.focus();}}}><div className="ui-select-options" role="listbox" aria-label={typeof label==="string"?label:"Options"}>{options.map((option,index)=><Button role="option" aria-selected={option.value===value} active={option.value===value||index===active} disabled={option.disabled} key={option.value} onPointerMove={()=>setActive(index)} onClick={()=>{onChange(option.value);setOpen(false);button.current?.focus();}}>{option.label}</Button>)}</div></div>,document.body)}</Field>}

type CheckProps=Omit<InputHTMLAttributes<HTMLInputElement>,"type"|"size">&{label:ReactNode;description?:ReactNode;error?:ReactNode};
export const CheckboxField=forwardRef<HTMLInputElement,CheckProps>(function CheckboxField({label,description,error,className="",...props},ref){return <label className={`ui-check ${error?"has-error":""} ${className}`.trim()}><input {...props} ref={ref} type="checkbox"/><span className="ui-check-mark" aria-hidden="true">✓</span><span><b>{label}</b>{description&&<small>{description}</small>}{error&&<small className="ui-field-error">{error}</small>}</span></label>});
export const SwitchField=forwardRef<HTMLInputElement,CheckProps>(function SwitchField({label,description,error,className="",...props},ref){return <label className={`ui-switch ${error?"has-error":""} ${className}`.trim()}><input {...props} ref={ref} type="checkbox" role="switch"/><span className="ui-switch-track" aria-hidden="true"><i/></span><span><b>{label}</b>{description&&<small>{description}</small>}{error&&<small className="ui-field-error">{error}</small>}</span></label>});
