import { cleanup, fireEvent, render, screen } from "@testing-library/react";
import { afterEach, describe, expect, it, vi } from "vitest";
import { Button, CheckboxField, ColorPickerField, FormField, FormLayout, IconPickerField, MultiValueToggleField, NumberField, SelectField, SwitchField, TextField } from "./controls";
import { HorizontalFaderField } from "./FaderControls";
afterEach(cleanup);

describe("shared controls",()=>{
  it("defaults buttons to a safe type and exposes semantic states",()=>{render(<Button variant="danger" loading>Delete</Button>);const button=screen.getByRole("button");expect(button).toHaveAttribute("type","button");expect(button).toBeDisabled();expect(button).toHaveClass("ui-danger");expect(button).toHaveAttribute("aria-busy","true");});
  it("associates field labels and errors",()=>{render(<TextField label="Name" error="Required" required/>);const input=screen.getByLabelText(/Name/);expect(input).toHaveAttribute("aria-invalid","true");expect(screen.getByRole("alert")).toHaveTextContent("Required");});
  it("renders number controls in minus, field, plus, keyboard order",()=>{const {container}=render(<NumberField label="Rows" min={1} max={3}/>);const control=container.querySelector(".ui-number-control")!;expect([...control.children].map((child)=>child.getAttribute("aria-label"))).toEqual(["Decrease value",null,"Increase value","Open number pad"]);expect(control.querySelector(".ui-input-keyboard")).toHaveTextContent("⌨");expect(screen.getByLabelText("Rows")).toHaveAttribute("inputmode","numeric");});
  it("opens a number-pad modal and commits its draft",()=>{const change=vi.fn();render(<NumberField label="Rows" min={1} max={3} onChange={change}/>);fireEvent.click(screen.getByRole("button",{name:"Open number pad"}));expect(screen.getByRole("dialog",{name:"Rows"})).toBeInTheDocument();fireEvent.click(screen.getByRole("button",{name:"3"}));fireEvent.click(screen.getByRole("button",{name:"ENTER"}));expect(change).toHaveBeenCalled();expect(screen.queryByRole("dialog")).not.toBeInTheDocument();});
  it("configures decimal input and hidden steppers",()=>{render(<NumberField label="Scale" allowDecimal showStepButtons={false}/>);expect(screen.getByLabelText("Scale")).toHaveAttribute("inputmode","decimal");expect(screen.queryByRole("button",{name:"Decrease value"})).not.toBeInTheDocument();fireEvent.click(screen.getByRole("button",{name:"Open number pad"}));expect(screen.getByRole("button",{name:"."})).toBeInTheDocument();});
  it("renders keyboard before clear, clears text, and opens the shared keyboard",()=>{const change=vi.fn();const {container}=render(<TextField label="Name" value="Wash" clearable onChange={change}/>);const control=container.querySelector(".ui-text-control")!;expect([...control.children].map((child)=>child.getAttribute("aria-label"))).toEqual([null,"Open keyboard","Clear input"]);fireEvent.click(screen.getByRole("button",{name:"Clear input"}));expect(change).toHaveBeenCalled();fireEvent.click(screen.getByRole("button",{name:"Open keyboard"}));expect(screen.getByRole("dialog",{name:"Name"})).toBeInTheDocument();});
  it("operates checkbox and switch controls with unified field labels",()=>{const change=vi.fn();const {container}=render(<FormLayout labelPlacement="side"><CheckboxField label="Dock" aria-label="Dock" checked onChange={change}/><SwitchField label="Fullscreen" aria-label="Fullscreen" checked onChange={change}/></FormLayout>);expect(screen.getByText("Checked")).toBeInTheDocument();expect(screen.getByText("On")).toBeInTheDocument();fireEvent.click(screen.getByRole("checkbox",{name:"Dock"}));fireEvent.click(screen.getByRole("switch",{name:"Fullscreen"}));expect(change).toHaveBeenCalledTimes(2);expect(container.querySelectorAll(".ui-form-field.labels-side")).toHaveLength(2);expect(container.querySelector(".ui-switch-control")).toBeInTheDocument();});
  it("selects one value from a shared multi-value toggle",()=>{const change=vi.fn();render(<MultiValueToggleField label="Stage view" value="2d" options={[{value:"2d",label:"2D"},{value:"3d",label:"3D"}]} onChange={change}/>);expect(screen.getByRole("radio",{name:"2D"})).toHaveAttribute("aria-checked","true");fireEvent.click(screen.getByRole("radio",{name:"3D"}));expect(change).toHaveBeenCalledWith("3d");});
  it("supports arbitrary horizontal fader ranges",()=>{const change=vi.fn();render(<HorizontalFaderField label="Environment brightness" value={1} minimum={0} maximum={2} step={0.05} display="100%" onChange={change}/>);const fader=screen.getByRole("slider",{name:"Environment brightness"});expect(fader).toHaveAttribute("max","2");fireEvent.input(fader,{target:{value:"1.5"}});expect(change).toHaveBeenCalledWith(1.5);});
  it("never lets the mouse wheel control a range fader",()=>{const change=vi.fn();render(<HorizontalFaderField label="Environment brightness" value={1} onChange={change}/>);const fader=screen.getByRole("slider",{name:"Environment brightness"});fader.focus();const wheel=new WheelEvent("wheel",{bubbles:true,cancelable:true,deltaY:10});fader.dispatchEvent(wheel);expect(wheel.defaultPrevented).toBe(true);expect(fader).not.toHaveFocus();expect(change).not.toHaveBeenCalled();});
  it("shows an immutable unit in the number input modal",()=>{render(<NumberField label="Distance" value="2.5" unit="m"/>);fireEvent.click(screen.getByRole("button",{name:"Open number pad"}));expect(screen.getByLabelText("Unit")).toHaveTextContent("m");expect(screen.getByLabelText("Distance value")).toHaveValue("2.5");fireEvent.click(screen.getByRole("button",{name:"←"}));expect(screen.getByLabelText("Unit")).toHaveTextContent("m");});
  it("opens a full-width picker, distinguishes selection from hover, and restores focus",()=>{const change=vi.fn();render(<SelectField label="Mode" value="main" options={[{value:"main",label:"Main"},{value:"own",label:"Own"}]} onChange={change}/>);const trigger=screen.getByRole("button",{name:/Main/});Object.defineProperties(trigger,{offsetWidth:{value:360},offsetHeight:{value:50}});vi.spyOn(trigger,"getBoundingClientRect").mockReturnValue({left:104.5,top:100,right:455.5,bottom:148.75,width:351,height:48.75,x:104.5,y:100,toJSON:()=>({})});fireEvent.click(trigger);expect(screen.getByRole("listbox")).toHaveStyle({width:"360px"});const selected=screen.getByRole("option",{name:"Main"}),hovered=screen.getByRole("option",{name:"Own"});expect(selected).toHaveClass("is-active");fireEvent.pointerMove(hovered);expect(hovered).toHaveClass("is-highlighted");expect(hovered).not.toHaveClass("is-active");fireEvent.click(hovered);expect(change).toHaveBeenCalledWith("own");expect(trigger).toHaveFocus();});
  it("dismisses the touch picker with escape",()=>{render(<SelectField label="Mode" value="main" options={[{value:"main",label:"Main"}]} onChange={()=>undefined}/>);const trigger=screen.getByRole("button",{name:/Main/});fireEvent.click(trigger);fireEvent.keyDown(window,{key:"Escape"});expect(screen.queryByRole("listbox")).not.toBeInTheDocument();expect(trigger).toHaveFocus();});
  it("supports side labels, multiple columns, and arbitrary field content",()=>{const {container}=render(<FormLayout labelPlacement="side" columns={2}><FormField label="Action"><Button>Run</Button></FormField></FormLayout>);expect(container.querySelector(".ui-form-layout")).toHaveClass("labels-side");expect(container.querySelector(".ui-form-layout")).toHaveStyle({"--form-columns":"2"});expect(screen.getByRole("button",{name:"Run"})).toBeInTheDocument();});
  it("selects catalog icons and colors",()=>{const icon=vi.fn(),color=vi.fn();render(<><IconPickerField label="Icon" value="◇" onChange={icon}/><ColorPickerField label="Color" value="#d98236" onChange={color}/></>);fireEvent.click(screen.getByRole("button",{name:/Choose icon/}));fireEvent.click(screen.getByRole("button",{name:"Use ★"}));expect(icon).toHaveBeenCalledWith("★");fireEvent.click(screen.getByRole("button",{name:/#D98236/}));fireEvent.click(screen.getByRole("button",{name:"Use color #1bd6ec"}));expect(color).toHaveBeenCalledWith("#1bd6ec");});
});
