use std::{
    collections::{BTreeMap, BTreeSet},
    time::Duration,
};

use uuid::Uuid;

use crate::{ActionContext, ActionError, ActionErrorKind};

#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct MacroId(pub String);

#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct MacroLanguageId(pub String);

#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct MacroExecutionId(pub Uuid);

#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub enum MacroCapability {
    QueryFixtures,
    QueryGroups,
    ChangeFixturePosition,
    AwaitTimer,
    AwaitEvent,
    AwaitOperatorInput,
    TriggerPlayback,
    Http,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct MacroDependency {
    pub kind: String,
    pub id: String,
    pub revision: Option<u64>,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct MacroDefinition {
    pub id: MacroId,
    pub revision: u64,
    pub language: MacroLanguageId,
    pub source: String,
    pub capabilities: BTreeSet<MacroCapability>,
    pub dependencies: Vec<MacroDependency>,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub enum MacroValue {
    Boolean(bool),
    Integer(i64),
    Text(String),
}

/// Language-visible invocation data. Trusted desk, user, session, and source identity are absent.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct MacroInvocation {
    pub id: MacroId,
    pub revision: u64,
    pub arguments: BTreeMap<String, MacroValue>,
}

/// Trusted application request used only by [`super::MacroService`].
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct MacroExecutionRequest {
    pub definition: MacroDefinition,
    pub context: ActionContext,
    pub arguments: BTreeMap<String, MacroValue>,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct GroupProjection {
    pub id: String,
    pub name: String,
    pub fixture_ids: Vec<String>,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum OperatorInputKind {
    Confirmation,
    Integer,
    Text,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub enum OperatorInputValue {
    Confirmed(bool),
    Integer(i64),
    Text(String),
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub enum MacroEventFilter {
    ShowRevision { show_id: Uuid, after_revision: u64 },
    Playback { playback_number: u16 },
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub enum MacroObservedEvent {
    ShowRevision { show_id: Uuid, revision: u64 },
    Playback { playback_number: u16 },
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub enum MacroWaitRequest {
    Timer {
        delay: Duration,
    },
    OperatorInput {
        prompt: String,
        kind: OperatorInputKind,
    },
    Event(MacroEventFilter),
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub enum MacroWaitState {
    Timer,
    OperatorInput { kind: OperatorInputKind },
    Event { filter: MacroEventFilter },
}

impl From<&MacroWaitRequest> for MacroWaitState {
    fn from(request: &MacroWaitRequest) -> Self {
        match request {
            MacroWaitRequest::Timer { .. } => Self::Timer,
            MacroWaitRequest::OperatorInput { kind, .. } => Self::OperatorInput { kind: *kind },
            MacroWaitRequest::Event(filter) => Self::Event {
                filter: filter.clone(),
            },
        }
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub enum MacroResume {
    TimerElapsed,
    OperatorInput(OperatorInputValue),
    Event(MacroObservedEvent),
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct MacroHttpPolicy {
    pub timeout: Duration,
    pub max_request_bytes: usize,
    pub max_response_bytes: usize,
    pub max_redirects: u8,
}

/// Language-visible HTTP data. Request and audit identities are generated by the scoped host.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct MacroHttpRequest {
    pub method: String,
    pub url: String,
    pub headers: BTreeMap<String, String>,
    pub body: Vec<u8>,
    pub audit_label: String,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct MacroHttpResponse {
    pub request_id: Uuid,
    pub status: u16,
    pub headers: BTreeMap<String, String>,
    pub body: Vec<u8>,
    pub audit_id: Uuid,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct MacroHttpTransportResponse {
    pub status: u16,
    pub headers: BTreeMap<String, String>,
    pub body: Vec<u8>,
    pub redirects: u8,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum MacroHttpTransportErrorKind {
    Timeout,
    Transport,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct MacroHttpTransportError {
    pub kind: MacroHttpTransportErrorKind,
    pub message: String,
}

impl MacroHttpTransportError {
    pub fn new(kind: MacroHttpTransportErrorKind, message: impl Into<String>) -> Self {
        Self {
            kind,
            message: message.into(),
        }
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub enum MacroHttpAuditEvent {
    Attempted {
        method: String,
        url: String,
        request_bytes: usize,
    },
    Terminal(MacroHttpTerminal),
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum MacroHttpTerminal {
    Succeeded { status: u16, response_bytes: usize },
    Failed { kind: MacroHttpFailureKind },
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum MacroHttpFailureKind {
    Cancelled,
    Policy,
    RequestLimitExceeded,
    ResponseLimitExceeded,
    RedirectLimitExceeded,
    Timeout,
    Transport,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub enum MacroAuditedAction {
    Http {
        request_id: Uuid,
        audit_id: Uuid,
        event: MacroHttpAuditEvent,
    },
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct MacroAuditEntry {
    pub execution_id: MacroExecutionId,
    pub macro_id: MacroId,
    pub correlation_id: Uuid,
    pub label: String,
    pub action: MacroAuditedAction,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum MacroErrorKind {
    Cancelled,
    Action(ActionErrorKind),
    LimitExceeded,
    Runtime,
    Host,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct MacroError {
    pub kind: MacroErrorKind,
    pub message: String,
    pub current_revision: Option<u64>,
    pub retryable: bool,
    pub audit_id: Option<Uuid>,
}

impl MacroError {
    pub fn new(kind: MacroErrorKind, message: impl Into<String>) -> Self {
        Self {
            kind,
            message: message.into(),
            current_revision: None,
            retryable: false,
            audit_id: None,
        }
    }

    pub fn action(kind: ActionErrorKind, message: impl Into<String>) -> Self {
        Self::new(MacroErrorKind::Action(kind), message)
    }

    pub const fn with_audit_id(mut self, audit_id: Uuid) -> Self {
        self.audit_id = Some(audit_id);
        self
    }
}

impl From<ActionError> for MacroError {
    fn from(error: ActionError) -> Self {
        Self {
            kind: MacroErrorKind::Action(error.kind),
            message: error.message,
            current_revision: error.current_revision,
            retryable: error.retryable,
            audit_id: None,
        }
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct MacroExecutionOutcome {
    pub completed: bool,
    pub host_actions: u32,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub enum MacroExecutionPhase {
    Queued,
    Running,
    Waiting(MacroWaitState),
    CancellationRequested,
    Completed(MacroExecutionOutcome),
    Cancelled,
    Failed(MacroError),
}

impl MacroExecutionPhase {
    pub const fn is_terminal(&self) -> bool {
        matches!(self, Self::Completed(_) | Self::Cancelled | Self::Failed(_))
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct MacroExecutionSnapshot {
    pub execution_id: MacroExecutionId,
    pub macro_id: MacroId,
    pub macro_revision: u64,
    pub phase: MacroExecutionPhase,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct MacroHostAction {
    pub expected_revision: Option<u64>,
}

impl MacroHostAction {
    pub const fn unversioned() -> Self {
        Self {
            expected_revision: None,
        }
    }

    pub const fn at_revision(expected_revision: u64) -> Self {
        Self {
            expected_revision: Some(expected_revision),
        }
    }
}
