//! A GDTF fixture type generated from a ToskLight fixture profile.
//!
//! An MVR names a GDTF file for every fixture, and a receiving application refuses the archive
//! when that file is absent. A profile imported from GDTF keeps its source archive, which an export
//! embeds unchanged; the shipped library and every profile authored on the desk exist only as
//! ToskLight profiles. This describes such a profile in the writer's subset: every mode with its
//! exact slots, byte widths, splits, defaults, Highlight values and function ranges, and one beam
//! per logical head. Wheels, emitters and 3D models are not reconstructed.

use super::{Channel, ChannelSet, FixtureType, GEOMETRY, Mode, Width, gdtf_name};
use crate::{
    ChannelFunctionBehavior, ChannelResolution, FixtureChannel, FixtureMode, FixtureProfile,
    ProfileError,
};
use std::collections::{HashMap, HashSet};
use uuid::Uuid;

/// Body edge in metres where the profile records no dimension, so the fixture is still drawn.
const DEFAULT_BODY_METRES: f32 = 0.3;

/// Packages every mode of `profile` as a `.gdtf` archive.
pub fn package_profile(profile: &FixtureProfile) -> Result<Vec<u8>, ProfileError> {
    super::package(&fixture_type(profile)?)
        .map_err(|error| ProfileError::Invalid(error.to_string()))
}

/// The DMX mode names the generated fixture type uses, in profile mode order.
///
/// GDTF names use a restricted character set and must be unique, so a profile's own mode name may
/// be adjusted. An MVR has to reference the adjusted name or the receiving application finds no
/// such mode.
pub fn mode_names(profile: &FixtureProfile) -> Vec<String> {
    let mut used = HashSet::new();
    profile
        .modes
        .iter()
        .map(|mode| unique(&gdtf_name(mode.name.trim()), "Mode", " ", &mut used))
        .collect()
}

/// Describes every mode of `profile` as one GDTF fixture type.
pub fn fixture_type(profile: &FixtureProfile) -> Result<FixtureType, ProfileError> {
    let (heads, beams) = beams(profile);
    let modes = profile
        .modes
        .iter()
        .zip(mode_names(profile))
        .map(|(mode, name)| {
            Ok(Mode {
                name,
                channels: channels(mode, &heads)?,
            })
        })
        .collect::<Result<_, ProfileError>>()?;
    let name = [&profile.name, &profile.short_name]
        .into_iter()
        .map(|name| name.trim())
        .find(|name| !name.is_empty())
        .unwrap_or("Fixture")
        .to_owned();
    let short_name = match profile.short_name.trim() {
        "" => name.clone(),
        short => short.to_owned(),
    };
    let manufacturer = match profile.manufacturer.trim() {
        "" => "Generic".to_owned(),
        manufacturer => manufacturer.to_owned(),
    };
    Ok(FixtureType {
        name,
        short_name,
        manufacturer,
        description: format!(
            "Generated by ToskLight from fixture profile revision {}",
            profile.revision
        ),
        id: profile.id.0,
        modes,
        body_size: Some(body_size(profile)),
        beams,
    })
}

/// Length (X), width (Y) and height (Z) in metres, from the profile's millimetre dimensions.
fn body_size(profile: &FixtureProfile) -> [f32; 3] {
    let physical = &profile.physical;
    [
        physical.width_millimetres,
        physical.depth_millimetres,
        physical.height_millimetres,
    ]
    .map(|size| {
        size.filter(|size| size.is_finite() && *size > 0.0)
            .map_or(DEFAULT_BODY_METRES, |size| size / 1000.0)
    })
}

/// Beam geometry names keyed by the heads they draw, and the fixture-wide list in first-seen order.
///
/// Every head except the shared master is a beam, and a head with the same name in several modes
/// is the same beam. A fixture whose only head is the shared master still gets one beam, because a
/// fixture type without one emits no light in a visualizer; its channels stay on the body, which
/// controls everything below it.
fn beams(profile: &FixtureProfile) -> (HashMap<Uuid, String>, Vec<String>) {
    let mut heads = HashMap::new();
    let mut order: Vec<String> = Vec::new();
    for mode in &profile.modes {
        let mut in_mode = HashSet::from([GEOMETRY.to_ascii_lowercase()]);
        for head in mode.heads.iter().filter(|head| !head.master_shared) {
            let name = unique(&gdtf_name(head.name.trim()), "Head", " ", &mut in_mode);
            if !order.iter().any(|known| known.eq_ignore_ascii_case(&name)) {
                order.push(name.clone());
            }
            heads.insert(head.id, name);
        }
    }
    if order.is_empty() {
        order.push("Beam".into());
    }
    (heads, order)
}

fn channels(
    mode: &FixtureMode,
    heads: &HashMap<Uuid, String>,
) -> Result<Vec<Channel>, ProfileError> {
    let primary = mode.primary_slots()?;
    let mut used = HashSet::new();
    mode.channels
        .iter()
        .map(|channel| {
            let geometry = heads.get(&channel.head_id).cloned();
            let (attribute, feature) = attribute(channel);
            // GDTF names a DMX channel after its geometry and attribute, so a second channel of one
            // head driving the same attribute needs an attribute of its own to stay addressable.
            let scope = geometry.as_deref().unwrap_or(GEOMETRY).to_ascii_lowercase();
            let mut name = attribute.clone();
            let mut index = 2;
            while !used.insert((scope.clone(), name.to_ascii_lowercase())) {
                name = format!("{attribute}_{index}");
                index += 1;
            }
            let width = width(channel.resolution);
            let max = width.max_raw();
            Ok(Channel {
                name: name.clone(),
                attribute: name,
                offset: primary[&channel.id],
                width,
                default: channel.default_raw.min(max),
                sets: sets(channel, max),
                fine_offsets: channel.secondary_slots.clone(),
                dmx_break: channel.split.max(1),
                geometry,
                feature: Some(feature.to_owned()),
                highlight: Some(channel.highlight_raw.min(max)),
                physical: physical(channel),
            })
        })
        .collect()
}

const fn width(resolution: ChannelResolution) -> Width {
    match resolution {
        ChannelResolution::U8 => Width::Byte,
        ChannelResolution::U16 => Width::Sixteen,
        ChannelResolution::U24 => Width::TwentyFour,
        ChannelResolution::U32 => Width::ThirtyTwo,
    }
}

/// Named ranges at their raw starts. GDTF sets cannot overlap, so functions of different priority
/// that start at the same value keep the first name.
fn sets(channel: &FixtureChannel, max: u32) -> Vec<ChannelSet> {
    let mut functions: Vec<_> = channel
        .functions
        .iter()
        .filter(|function| function.dmx_from <= max)
        .collect();
    functions.sort_by_key(|function| function.dmx_from);
    functions.dedup_by_key(|function| function.dmx_from);
    functions
        .into_iter()
        .map(|function| ChannelSet {
            name: match &function.behavior {
                ChannelFunctionBehavior::Fixed { label, .. }
                | ChannelFunctionBehavior::Indexed { label, .. }
                    if !label.trim().is_empty() =>
                {
                    label.clone()
                }
                _ => function.name.clone(),
            },
            from: function.dmx_from,
        })
        .collect()
}

fn physical(channel: &FixtureChannel) -> Option<(f32, f32)> {
    let from = channel.physical_min.unwrap_or(0.0);
    let to = channel.physical_max.unwrap_or(1.0);
    (from.is_finite() && to.is_finite() && (to - from).abs() > f32::EPSILON).then_some((from, to))
}

/// The GDTF attribute for a channel's canonical attribute, and the feature it belongs to.
///
/// Standard names let a receiving console or visualizer treat a channel as the dimmer, pan or
/// colour mix it is; anything without a standard counterpart keeps its own name as a control.
fn attribute(channel: &FixtureChannel) -> (String, &'static str) {
    let key: &str = &channel.attribute.0;
    let standard = match key {
        "intensity" => Some(("Dimmer", "Dimmer.Dimmer")),
        "pan" => Some(("Pan", "Position.PanTilt")),
        "tilt" => Some(("Tilt", "Position.PanTilt")),
        "color.red" => Some(("ColorAdd_R", "Color.RGB")),
        "color.green" => Some(("ColorAdd_G", "Color.RGB")),
        "color.blue" => Some(("ColorAdd_B", "Color.RGB")),
        "color.white" => Some(("ColorAdd_W", "Color.RGB")),
        "color.warm_white" => Some(("ColorAdd_WW", "Color.RGB")),
        "color.cold_white" => Some(("ColorAdd_CW", "Color.RGB")),
        "color.amber" => Some(("ColorAdd_A", "Color.RGB")),
        "color.lime" => Some(("ColorAdd_GY", "Color.RGB")),
        "color.uv" => Some(("ColorAdd_UV", "Color.RGB")),
        "color.cyan" => Some(("ColorSub_C", "Color.RGB")),
        "color.magenta" => Some(("ColorSub_M", "Color.RGB")),
        "color.yellow" => Some(("ColorSub_Y", "Color.RGB")),
        "color.temperature" => Some(("CTC", "Color.Color")),
        "color.wheel" => Some(("Color1", "Color.Color")),
        "shutter" => Some(("Shutter1", "Beam.Beam")),
        "strobe" => Some(("Shutter1Strobe", "Beam.Beam")),
        "zoom" => Some(("Zoom", "Beam.Beam")),
        "iris" => Some(("Iris", "Beam.Beam")),
        "focus" => Some(("Focus1", "Focus.Focus")),
        "frost" | "frost.1" | "softness" => Some(("Frost1", "Beam.Beam")),
        "frost.2" => Some(("Frost2", "Beam.Beam")),
        _ => None,
    };
    if let Some((name, feature)) = standard {
        return (name.to_owned(), feature);
    }
    if let Some(gobo) = key
        .strip_prefix("gobo.")
        .and_then(|rest| wheel(rest, "Gobo"))
    {
        return (gobo, "Gobo.Gobo");
    }
    if let Some(prism) = key
        .strip_prefix("prism.")
        .and_then(|rest| wheel(rest, "Prism"))
    {
        return (prism, "Beam.Beam");
    }
    match gdtf_name(&key.replace('.', "_")) {
        name if name.trim().is_empty() => ("Control".to_owned(), "Control.Control"),
        name => (name, "Control.Control"),
    }
}

/// `1` → `Gobo1`, `1.rotation` → `Gobo1PosRotate`.
fn wheel(rest: &str, prefix: &str) -> Option<String> {
    let (index, suffix) = rest.split_once('.').unwrap_or((rest, ""));
    if index.is_empty() || !index.bytes().all(|byte| byte.is_ascii_digit()) {
        return None;
    }
    match suffix {
        "" => Some(format!("{prefix}{index}")),
        "rotation" => Some(format!("{prefix}{index}PosRotate")),
        _ => None,
    }
}

fn unique(base: &str, fallback: &str, separator: &str, used: &mut HashSet<String>) -> String {
    let base = if base.trim().is_empty() {
        fallback
    } else {
        base
    };
    let mut candidate = base.to_owned();
    let mut index = 2;
    while !used.insert(candidate.to_ascii_lowercase()) {
        candidate = format!("{base}{separator}{index}");
        index += 1;
    }
    candidate
}

#[cfg(test)]
#[path = "profile_tests.rs"]
mod tests;
